### ISSUE TITLE
How do I read CSVIssuesReport.csv?

### ISSUE THREAD

**Issue by jrattanpal** [forcedotcom/SFDX-Data-Move-Utility#102]
I get these warnings for CSVIssues but I don't know how to solve that. I am using "select all" in the export file for my objects as I want all the data.

Do I simply ignore it?

All 3 files (export.json, CSVIssuesReport and Log) are attached. (had to rename to .txt)

[CSVIssuesReport.csv.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4813681/CSVIssuesReport.csv.txt)
[2020-06-22__10_06_45.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4813685/2020-06-22__10_06_45.log)
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4813686/export.txt)

**Comment by hknokh** [comment]
Hello, @jrattanpal 
In your queries you are using "all" meaning all fields of the object. The plugin actually replaces "all" with all object's fields. The first step of the processsing that the plugin scans the csv source csv files and actually didn't find some corresponding columns to those fields that were extracted by "all" select. This is the error: COLUMN DEFINED IN THE   SCRIPT IS MISSING IN THE CSV FILE.
This one: CSV FILE DOES NOT EXIST says that you are missing csv source files for the listed objects or maybe your script object contains lookup field to this object and the plugin wants its source data. 
Fields warning is not critical if you don't want to update those fields. If csv field does not exists values will be undefined.
Missing files is more critical because you are missing data for those objects and may cause issues of searching for lookup parent records.
Try to limit "all" do not include redurand fields.
You have excludedFields property of object that you can list useless fields.

**Comment by jrattanpal** [comment]
Hi,

For the fields, 

I have about 20-30 objects that need to go in that. ANd each of those may have 20-30 fields. It's very hard to list all of those. And even harder to figure out which ones are actually needed.

I was just surprised as I used the "all" option and it was the plugin that decided which fields are needed. So I thought those shouldn't be an issue. 

But I guess that's how plugin resolves it?? I still don't understand why it added those fields automatically and then complaining about it. That's my main confusion. 

For the CSV file, 

that is also automated by plugin. I am getting Location (SELECT all FROM Location) object. That in return is getting "Address" object.

I am not sure how to fix that.

**Comment by hknokh** [comment]
Hi @jrattanpal 

For the fields.
Again, the plugin works step-by-step and can't predict what will happen on the next step to go back and start the process again from the beginning with updated configuration.

- First step is to add fields when all is used.

- Next step is to check files - if missing - it will alert you.

The solution:
When you are creating the CSV files simply include those objects (that you don't want to export but need their data in the CSV files) in your configuration with **Readonly** operation.
So their data will apear in the corresponding CSVs.
Then do the import with the ame export.json.
Since it is readonly - don't worry about to get the records inserted to the target - the would not be inserted.
