### ISSUE TITLE
[QUESTION]- JavaScript heap out of memory

### ISSUE THREAD

**Issue by aojedo** [forcedotcom/SFDX-Data-Move-Utility#119]
**Description**
When running the tool for a subset of records that account for less than 2000 in the source Org, the execution runs out of memory.
Also, the logs show the tool retrieving records "WHERE Id IN ()" with a set of IDs, when none of my where clauses were made like that.
Finally, knowing that I filtered less than 2000 records in, the tool tries to retrieve more than 200k Account records, and don't know why.
I'm using Data Move Utility GUI.

**To Reproduce**
Execute it from my customers full copy

**Expected behavior**
Id' like it not to crash :)

**export.json**
**Log file**
Attached
[SFDX DMU.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4846675/SFDX.DMU.zip)

**Comment by hknokh** [comment]
Hello @aojedo 
I reviewed your export.json.  

The issue with the records that are not limited is the correct behavior according to your configuration. 
Pay attention that you are using allRecords: false in all objects and in this case - the tool will **NOT** limit the records **ONLY** by the LIMIT 500 clause!  
When allRecords is false, it indeed will take the 500 random records, but next it will also scan all records of all other objects having parent lookups to this object to find referenced parent records and if found - will add them into the record set. Hence one object causes adding records to other one and they always affect each other... 
Normally if you want to limit the records for sure, you need to have at least one object (or all objects, it's up to you) with allRecords = true (or master=true because the allRecords parameter is deprecated and was repalced, but I had no time to update the Desktop App and it does snot reflect the latest plugin changes). This object called the "master" object and you can have as many "master" objects as you want. The "master" object will always limited by your LIMIT clause. Other records with master=false called "slave" or "child" objects and they will be automatically fitted to all the "master" objects in your configuration. 
You need to play with the parameters to have a best configuration that fits your needs. 
Refer [https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.) about the master (allRecords) parameter. Also refer here [https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/7.-Troubleshooting.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/7.-Troubleshooting.) how to extend the heap memory for large record sets.
