### ISSUE TITLE
read ECONNRESET error during "Retrieving the source data (step 1)" stage

### ISSUE THREAD

**Issue by EliasLahham** [forcedotcom/SFDX-Data-Move-Utility#12]
Sorry in advance for spamming issues to you guys, but I'm getting this error when attempting to fetch data from prod:

![image](https://user-images.githubusercontent.com/17418745/78382890-846cd500-75a5-11ea-9d86-04ce8f0a84a3.png)

The sObject I'm fetching has around 90k records and when this error occurs the command stays in progress, but doesn't do anything. This isn't specific to this sObject, it happened on another sObject of mine.

Thanks in advance

**Comment by hknokh** [comment]
Hello @EliasLahham 
ECONNRESET typically can say 3 things:
1) Internet connection interrupted.
2) Remote server stopped to respond (but not real that the Salesforce is down..).
3) Remote call timeout issue due large data and/or slow internet connection.
But most likely that you have an timeout issue. 
For calling to the Salesforce I am using jsforce library that unfortunatelly has only constant timeout value (don't know exactly how much in ms is it because it's not documented) and the library does not provide option to increase it.
From my side I did change to the threshold when switching from the REST Api to the bulk query api from 100K to 30K records. Please try again to fetch your recordset of 90K if  you are still facing the same issue.
Regards.
