### ISSUE TITLE
[FEATURE REQUEST]- Batch Size for Bulk API Query

### ISSUE THREAD

**Issue by pelim** [forcedotcom/SFDX-Data-Move-Utility#140]
i didn't found an option to control the batch size for bulk select queries and would like to control this, actually i need to increase the node memory limit to 16GB for selecting 700.000 Accounts, not sure if this will help

**Comment by hknokh** [comment]
Hello, @pelim  
There is no option technically to increase the Batch Size of Builk Api query.
The only option is to increase the node memory size.
Even if we had have option to increase the Batch Size - it will not solve the memory issue because the Plugin uses JS maps and arrays to store the records internally at runtime and by default only 512Mb is allocated. You can understand that it is not anough to hold 700k records.

**Comment by hknokh** [comment]
Another option to limit records by LIMIT or WHERE

**Comment by pelim** [comment]
@hknokh  is it required to have all the lines in the memory?

**Comment by hknokh** [comment]
@pelim , of course, because the Plugin makes a lot of record comparing and lookup matching on regular basis across all migration steps between all objects in the configuration. 
In additional each object is being updated several times in several migration steps in many kinds....
So it is strongly necessary to keep all in memory.  
Are you having any problem to increase the nodejs memory or limiting records with the SOQL? 
This is how to do that:
[https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/7.-Troubleshooting.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/7.-Troubleshooting.)
