### ISSUE TITLE
[BUG]-Cannot read property 'child__rSFields' of undefined

### ISSUE THREAD

**Issue by kamalsomu** [forcedotcom/SFDX-Data-Move-Utility#158]
**Describe the bug**
I am getting an error when trying to export csv file from source environment

This has occurred when i have tried to multi select fields using "all" keyword for the case object.

**export.json**
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5044678/export.txt)

**Log file**
[2020-08-08__10_24_13.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5044676/2020-08-08__10_24_13.log)

**Comment by kamalsomu** [comment]
I have tried multiselecting

**Comment by hknokh** [comment]
Hello, @kamalsomu 
This is kind of errors that I could not reproduce on my side, because it's depend on the specific metadata of the org.
There is two option here, you can try to download the source code of the Plugin and locate the root case of the issue then tell me to fix, or if you have the playground org that I can reproduce it there you can give me the access to investigate the issue.
Thanks

**Comment by kamalsomu** [comment]
> Hello, @kamalsomu
> This is kind of errors that I could not reproduce on my side, because it's depend on the specific metadata of the org.
> There is two option here, you can try to download the source code of the Plugin and locate the root case of the issue then tell me to fix, or if you have the playground org that I can reproduce it there you can give me the access to investigate the issue.
> Thanks

The salesforce environment that I have tried is the brand new Einstein analytic enabled developer edition which I have signed from this link.(https://developer.salesforce.com/promotions/orgs/analytics-de). I have not created any other custom metadata in that edition.

Could you please try with this edition or if you want to provide you the access for the edition, can I know your email Id?

**Comment by hknokh** [comment]
Please provide the access fo the instance that you are facing the issue with to haim.knokh@gmail.com

**Comment by hknokh** [comment]
@kamalsomu 
I created the edition and am able to reproduce the issue, I will fix it and let you kno when done.

**Comment by kamalsomu** [comment]
@hknokh I was about to give the login access :) Thanks a lot for the update. :)

**Comment by hknokh** [comment]
@kamalsomu 
I've fixed the issue, please update the plugin and retry.
In addition I want to point you on some concideration regarding your export.json.

- You didn't set any externalid for the Account and Case. In this case the Plugin will try to detect the possible external id automatically, for the Account it's name and for the Case it's CaseNumber. During the export execution you can see the warning  WARNING: [WARN] Field Case.Name is missing in the Target. It's normally and you can disregard it, since the Plugin initially put Name field as external id for the Case object before querying the metadata, so it will complain about missing field, then it replaces the Name with CaseNumber and will proceed without issue.
- Since you put LIMIT 5 for Account, I suggest you also to put the Case object that has lookup to Account into **master = false**, so the Plugin will automatically match the case records to the limited Account records while fetching from the Source org. 
This will also prevent fetching extra Case records and will prevent apearing of the Missing Lookup Records warnings when you will import the generated csv files back into the target org later.
You can learn about meaning of **master** parameter here: [https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.)

Below the suggested modification of your export.json file:

{  	
"objects": [{
		"query": "SELECT Id,Name,BillingAddress FROM Account limit 5",
		"operation": "Readonly"
	},{
		"query": "SELECT all FROM Case",
		"operation": "Readonly",
		**"master": false**
	}  
    ]
}
