### ISSUE TITLE
[FEATURE REQUEST]- Configuration for matching the maximum number of child records from the master record

### ISSUE THREAD

**Issue by kamalsomu** [forcedotcom/SFDX-Data-Move-Utility#160]
Say I have millions of case records associated to each account record. I would need to only migrate a maximum of 1000 most recent case records associated to each account object.Is there any configuration available to limit to suffice this requirement?

Also, is there an configuration where the user can itself set the priority for each object to be processed in an order along with above requirement?

**Comment by hknokh** [comment]
Hello @kamalsomu 

Regarding the first question:
For the master object simply use query like:
**SELECT......... ORDER BY LastModifiedDate DESC LIMIT 1000** + **master:true** (or none since it's default option)
For other objects you can set **master:false** and the Plugin will try to detect automatically which subset of records should be processed using the parent-child lookup relationships.

Regarding the second question:
There is no such option to set order of processed objects explicitly. 
I will add this feature to the development roadmap.

**Comment by kamalsomu** [comment]
@hknokh Thank you for including in the roadmap. 

To clarify more on the first question that I have asked, I don't want all the subset of the records.. I only want some minimum records from the subset of records :)

**Comment by hknokh** [comment]
What does it mean minimum?

**Comment by kamalsomu** [comment]
@hknokh So If I have a maximum of 1000 cases associated to an account. I need only "**minimum**" of 100 recent cases from an account for migration which I can configure it by using some criteria in the configuration.

**Comment by hknokh** [comment]
Dont understand you sorry. Select 100 cases order by date modyfied desc and put where accountid != null  ?

**Comment by kamalsomu** [comment]
@hknokh  Sorry, I have attached the image on my expectation. 

![hk](https://user-images.githubusercontent.com/11818325/89991060-e6022600-dca0-11ea-9d8d-a0ce09290402.jpg)

**Comment by hknokh** [comment]
So it's recent n cases per account.
I need to think how it can be accomplished.

**Comment by kamalsomu** [comment]
@hknokh Yes, thats exactly what my expectation is. If that could be made along with setting the order for the object to be processed, it would be really helpful to migrate the data for different use cases if I need to include all the subset of records or the recent n child records per master object. Thanks for your time. :)
