### ISSUE TITLE
[BUG]-Upsert using mocked ExternalId

### ISSUE THREAD

**Issue by gidglass** [forcedotcom/SFDX-Data-Move-Utility#162]
**Describe the bug**
We have a custom "ExternalId__c" field on most objects in our org that was previously used by other tooling to migrate data between environments. If records are created directly in the SOURCE org, then this field is not populated. Instead, when migrating data, the record Id would be mapped and used instead.

We are leveraging the mocking functionality of the SMFDMU plugin to accomplish the same thing (see `export.json` below). If `ExternalId__c` in the source org is blank, then "mock" it using "ids" pattern to map the record id.

This works _perfectly_ on INSERT/UPDATE operations. However, if we have operation set to UPSERT, then we run into issues. On first run (i.e. TARGET has no records), then all data is inserted correctly. But on subsequent runs, the plugin incorrectly tries to re-insert the records instead of updating them and throws a duplicate Id error. For example (line from target csv file):

```
... BGC_Code__c duplicates value on record with id: a0Z7A000008ZIPm
```
My hunch is that the plugin is first creating the `.insert` csv and _then_ mapping the ExternalId__c field.

**To Reproduce**
1. In SOURCE, create record with an ExternalId__c field that is blank
2. In `export.json`, set ExternalId => ExternalId__c and mock it with `ids` pattern (see export.json below)
3. Run plugin with `Upsert` operation
4. Re-run the plugin _again_ with `Upsert` operation

**Expected behavior**
I would expect the plugin to use the mapped value in determining whether these records are new or already exist in the TARGET org (i.e. no need to update anything)

**export.json**
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5091418/export.json.txt)

**Log file**
[2020-08-18__10_55_25.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5091391/2020-08-18__10_55_25.log)

**Comment by hknokh** [comment]
Hello @gidglass 

I understand your issue, but it's not a bug, because this is exact how the Plugin built and I would highly **not recommend(!)** to use mocking feature on the external id fields.
When the mocking feature is active, the executing order is as following: 
- **First step**:  the Plugin compares the source and the target records for the differences need to be updated. 
- **Second step**(just before inserting/updating values into the target):   it rundomizes the values and updates the target. 
So, the randomized values **will have no any impact** on the other data, because they are used only once to update the target and getting lost after that.

- **For the Upsert:**  Don't anonymize you externalid or set **deleteOldData = true** to remove old data.
- **For the Insert:** When Inserting, the Plugin always use RecordID as external id in background (regardless what you set in the export.json), so it will work even external id is randomized).
- **For the Update:** It simply not found any matching records at the target end (as I described above) - so will do nothing.

**Comment by gidglass** [comment]
Thanks for the feedback - will take this away and modify accordingly.
