### ISSUE TITLE
[BUG]-Didn't understand relationship 'Contact' in field path.

### ISSUE THREAD

**Issue by nmhegde** [forcedotcom/SFDX-Data-Move-Utility#163]
**Describe the bug**
When trying to load Opportunity Data from Source to Destination it is trying to retrieve Contact standard field which not at all present on the opportunity Object as a standard field. 
**To Reproduce**
Run the plugin with the given Export.json file

**Expected behavior**
It should not try to retrieve contact object data because it is not a standard field on Opportunity Object
**export.json**
`{
    "objects": [
        {
            "query": "SELECT Id, Name, RecordTypeId,custom_false FROM Opportunity LIMIT 20",
            "operation": "Upsert",
            "externalId": "Name"
        }
    ],
    "bulkThreshold" : 5,
    "bulkApiV1BatchSize" : 5,
    "bulkApiVersion" : 1.0
}`

**Log file**
[2020-08-19__12_15_11.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5098906/2020-08-19__12_15_11.log)

**Comment by hknokh** [comment]
Hello,
The field Pricebool2Id appears as the standard field for the opportunity object.
Try to run in the Developer Console:
System.debug(Opportunity.sObjectType.getDescribe().fields.getMap().get('Pricebook2Id').getDescribe().custom);
You will get false that is indicating that it's standard object.
So this field will be added by the plugin when using **custom_false** 
If you don't want this field to be migrated, exclude it using "excludedFields" property for the script object.
Refer:
[https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/2.2.-Full-configuration.)

**Comment by nmhegde** [comment]
I was mentioning the Contact field which is getting pulled as a standard field which is not true in that case. You can see that error in the log.

**Comment by hknokh** [comment]
Ok, np, why Contact is not a standard field on the Opportinuty???

The same:
System.debug(Opportunity.sObjectType.getDescribe().fields.getMap().get('ContactId').getDescribe().custom);

So, again: **all sobject fields** that have **"custom = false"** in their sfield descriptions will be included and you need manually exclude them.

**Comment by hknokh** [comment]
We are talking about lookup fields, the Plugin is about to process lookup field s like ContactId, Prisebook2Id, AccountId etc. Maybe this is what get  you confused.

**Comment by shawnholt** [comment]
Using the GUI App, I have the  same error:
[ERROR] Error during execution of the command:
RecordType.NamespacePrefix, RecordType.SobjectType, Contact.Name FROM Opportunity
ERROR at Row:1:Column:1836
Didn't understand relationship 'Contact' in field path. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names..

The Query fails at the end: 
 AccountId, CampaignId, OwnerId, Pricebook2Id, RecordTypeId, ContactId FROM Opportunity - Perhaps there is a transformation that is failing from Contact.Id to Contact Name

**Comment by hknokh** [comment]
Hello @shawnholt 

Sorry for the late reply.

Anyway, as I understand you are using Name field as externalid for the Contact object. 
You are absolutelly right that the query SELECT AccountId, CampaignId, OwnerId, Pricebook2Id, RecordTypeId, **Contact.Name** FROM Opportunity is not valid. 

But, since the Plugin can't directly bind the source contactid to the target contactid without using the intermediate external id field (in this case it's the Name field), so it always necessary make a transformation similar to ContactId => Contact.Name (which is not correct) or for sample AccountId => Account.Name (which is valid).

I think, the ContactId lookup for Opportunity is populated automatically when AccountId is populated, so as a  solution I can advise you to remove ContactId from the source query, like:
SELECT AccountId, CampaignId, OwnerId, Pricebook2Id, RecordTypeId FROM Opportunity

**Comment by hknokh** [comment]
This case is considered resolved
