### ISSUE TITLE
[BUG]-Support more than 50k record per object on upsert

### ISSUE THREAD

**Issue by yahirah** [forcedotcom/SFDX-Data-Move-Utility#165]
I'm using the tool for a migration between two productions and I encountered one significant problem, which make it impossible to use it, as there is no way of overcoming it. The Update feature does not work if there is more than 50k record in an org 
Scenario to replicate:
1. Prepare a file with 100 k records.
2. Try to import it using Upsert operation with some External Id.
3. Assume 80k records save without problems, 20k failes because of some custom validation.
4. Turn off the problematic validation and run the script again.
5. There will be 50k records in an insert call (even though there are 80k records in an org), and 30k of them will fail with "Duplicate External Id" error (obviously), the other will pass.
6. There will be only 50k record in an update call.

**Describe the solution you'd like**
I would like for this tool to support upsert operation for at least 300 000 records (for now ;)), but if the tool should be a real competitor to Data Loader, it should support operations with up to 5 mln records. Otherwise it can trully only be use as a scratch org loader.

**Comment by hknokh** [comment]
Hello @yahirah 

- **Regarding the memory issues  and capacity.**

The Plugin does support 300000+ records (me and some ofher users actullay used it in 700k+ records).
For the large datasets maybe will need to increase the nodejs memory:
[https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/7.-Troubleshooting.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/7.-Troubleshooting.)

- **Regarding the upserted records that less then expected + duplicate id problem.**
I don't know the configuration you used, but I believe that it's like the configuration problem.
Someone opened the similar bug when tried to put the anonymization on the externalid field (in this case it's normal, because external ids should not be anonymized). But can't say you until you will provide more details (export.json + log), since as per your description I could not able to reproduce the issue.

-------
And in the summary, it's already now a real great sf DataLoader competitor (but not so known yet), even it will be able to load only up to 10k records (but really it can do it perfectly) :)  because the DataLoader can't deal with multiple objects + person accounts + upsert by any external id field + field mappings + 1000+ other awesome features :)
For the single object (imort / export object per object + manual dialing with lookups using excel file) the DataLoader can be used without any problem and will work perfectly.

**Comment by yahirah** [comment]
@hknokh I would love to believe that this is a problem with configuration, but the same configuration worked on previous 20 objects, that just happend to be less then 50 k in size.

*Export.json*
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5117404/export.txt)
The object I am concerned about is called Project_Worklog__c (mapped to Worklog__c) in mapping:
[FieldMapping.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5117457/FieldMapping.txt)

*Log from initial Insert*
[2020-08-23__01_33_20.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5117432/2020-08-23__01_33_20.log)
*Log from update*
[2020-08-23__11_16_32.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5117458/2020-08-23__11_16_32.log)
Every log after initial insert were 100 000 successfull updates, few thousands successfull inserts (when I fixed some validation error) and thousands of failed inserts(!) with info about duplicated external id entry.... on field, which should be used as an external id for upsert.
*The error I am receiving*: "DUPLICATE_VALUE:duplicate value found: Migration_OriginalId__c duplicates value on record with id: a2x0Q0000006e20". I've checked the Id, this the exact same record that the tool was trying to insert, it has Migration_OriginalId__c properly set up, it is not empty or anything like that, I do not have duplicate entries in my import file.

*Clipped file with insert results*:
[Project_Worklog__c_insert_target_example.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5117454/Project_Worklog__c_insert_target_example.txt)

My command:  sfdx sfdmu:run --sourceusername csvfile --targetusername spectrum-uat -p ".\folderName\"
The are no automations that could change the value of the Migration_OriginalId__c  field - it is created by Python script directly in the csv file, and it is not mentioned or used anywhere else except for the mapping in export.json. The same code and setup worked for many different objects - all of them with size of less then 50k.

I agree that this tool is great, that's why I have chosen it and trying to learn and use in my project for last few weeks, and have plan for using it in production environment in following weeks. 
I would just wish for more documentation on different use cases, because if there is really an error with configuration, I assume it is somewhat about using csv file as a source files. And most of my problems with this tool was connected to "when you are using  csv files, you need to do that and that" and those things were not mentioned (at that time) in the docs (which I know by heart already :) ). But I understand, someone must be the first to clean the new paths ;) 
I keep fingers crossed that you could help me find the solution to this problem.

**Comment by yahirah** [comment]
I also double checked what is in the org. Before running script again I queried the object:
[SELECT COUNT(Id) FROM Worklog__c] = 248586
The logs from the script:
{Project_Worklog__c} Mapping records returned from the API... The target object: Worklog__c.   
{Project_Worklog__c} Retrieving the TARGET data has been completed. Fetched 100000 new records.
So it really looks like some kind of limit set up somewhere. Is this some kind of default setting?

**Comment by hknokh** [comment]
Thank you for the update.
I will check from my side and let you know.

**Comment by hknokh** [comment]
Hello @yahirah 

I had no really a lot of time to tackle your issue (because of overload in my work this week), but from the quick overview what I see here:

- Regarding the limitation of 100k.
Yeap, there is a limitation of fetching up to 100000 records while using rest api as fetching engine instead of bulk query api.
The Plugin decides by itself whether to use rest or bulk for the record fetching, according to the predicted size of the records to be fetched and **before they are actualy fetched.** This limitation is done to save the resources and for the best perfomance.

The issue is coming from the field mapping, the engine measures the total amount of the records of sObject called **Project_Worklog__c** but in real it uses **Worklog__c** due to the field mapping. That is why it switches into the rest mode althoug actually there are more records in the target.
I need to check and fix it it.

- Regarding the duplicate records.
Yesterday somebody opened the similar issue with duplicates and he provided me an access to his org to debug. Maybe this is the same root case as yours.  
I also need to check.

The most likely that the both issues are coming from the incorrect working of the field mapping.
Will keep you  updated further.

**Comment by hknokh** [comment]
@yahirah 
The update:
I've fixed the issue of 100k limit as I said above.
Please reinstall the plugin to latest 3.5.11 and recheck for this part and let me know.

**Comment by yahirah** [comment]
Everything works now, thank you very much.

**Comment by hknokh** [comment]
Good news @yahirah 
Is the duplicate id error also fixed ? As for me, I did nothing on it yet  )

**Comment by yahirah** [comment]
The duplicate id error was caused by, well, duplicates in the org. When I had, let's say, 150 000 records on the org, but 200 000 to upsert, and only 100 000 was retrieved, the 50 000 already existing was being inserted using external id, which already existed on the org. 
So, fixing the issue with retrieving all existing records fixed the issue with duplicates for me.
