### ISSUE TITLE
[BUG]-Cannot read property 'child__rSFields' of undefined (FSL)

### ISSUE THREAD

**Issue by 4an70m** [forcedotcom/SFDX-Data-Move-Utility#210]
Hi! I'm running export for an FSL (Field Service Lightning) object - ServiceTerritory, against a sandbox org. Getting the  

> Cannot read property 'child__rSFields' of undefined.

To reproduce, you would need an org with FSL enabled so it's not an easy task. 
As a part of a quick fix, I've changed
```
   thisField.__rSField = __rSField;
   __rSField.idSField = thisField;
   parentExternalIdField.child__rSFields.push(__rSField);
}
```
to: 
```
   thisField.__rSField = __rSField;
   __rSField.idSField = thisField;
   if(parentExternalIdField) {
      parentExternalIdField.child__rSFields.push(__rSField);
   }
}
```
directly in `...\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\script.js:239:43`. I've got no idea if it breaks anything else since I didn't study the source code properly, merely added a null-check.

[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5292170/export.txt)

[2020-09-28__14_25_15.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5292223/2020-09-28__14_25_15.log)

**Comment by hknokh** [comment]
Hello, 
I had already fixed this bug at the past, but seems that it's back again in your case...
The root case of the issue is because there is a **all** keyword in the query string, so the Plugin brings some lookup field into the query string and then tries to automatically resolve the parent sobject (since it was not included directly in the export.json) and also to detect it's default (optimal) externalId, but failed to do that properly.
Your patch indeed will impact other functionality and it's not correct. However for the meantime, to not break the process, I put try/catch block with warning message to indicate which sobject and field causes the issue. 
Please check again and send me the latest log. 
Possible I will be able to get more relevant solution further, but normally need to debug it on your end.

**Comment by 4an70m** [comment]
Hi @hknokh 
Thank you so much for the update, it works like a charm! Sharing the latest export.json and log file with you. It appears the lookups from ServiceTerritory object to other ServiceTerritories are what's causing the problem.

[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5297861/export.txt)

[2020-09-29__12_03_43.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5297864/2020-09-29__12_03_43.log)
