### ISSUE TITLE
[BUG]-Custom User Lookup Fields Not Populating in Target

### ISSUE THREAD

**Issue by skostojohn** [forcedotcom/SFDX-Data-Move-Utility#240]
**Describe the bug**
Migrating a simple custom object containing custom user lookup fields; the values for the custom lookup fields are not being populated in the target.

**To Reproduce**
Create a custom object with a custom user lookup field in two Salesforce environments.  Create a record in one environment and attempt to migrate it to the other environment using sfdmu plugin to sfdx cli, using the multiselect "all" in your query.

**Expected behavior**
All fields, including custom user lookup fields, are populated in the target.

**export.json**
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5626306/export.json.txt)

**Log file**
[2020-12-01__16_40_14.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5626308/2020-12-01__16_40_14.log)

Thank you for your help!!

**Comment by hknokh** [comment]
Hello @skostojohn 

The user lookups are definitely not included into the multiselect keywords by the Plugin implementation. You need to add them manually in the query string besides **all** multiselect keyword that you are using.

Also, make sure that user Names are identical in both environments, because it's a default externalId the Tool is choosing for the User object. Alternatively, in case you need to switch the external id to another User object field, you must add the User object into the **objects** array of the export json with Readonly operation and set the externalId property to different field you want to use.

**Comment by skostojohn** [comment]
Adding the lookups manually worked.  Thank you!  

You might consider adding this to the documentation - I assumed the query keyword "all" would include lookups, and others might make the same mistake.
