### ISSUE TITLE
Lookup problem

### ISSUE THREAD

**Issue by kowszymon** [forcedotcom/SFDX-Data-Move-Utility#243]
Hello,
I am trying to upsert ivybase__Route_Details__c records which have lookup to ivybase__Route__c object. When there is no data in my org I can insert 9000 out of 11000 records successfully, the rest fails due to heap size error. Then I try to do the same operation again to insert the 2000 records left. But in the next run the field Route__c which is a lookup to ivybase__Route__c, as well as ivybase__Store__c which is a lookup to Account are empty on all of the records and they all fail. On the source org all of the records have these fields fulfilled. Am I doing something wrong or is this a bug?

Please find attached my export.json file.

/Users/szymonkowalczyk/Documents/Projects/SFDX Data Move Utility 2/SFDX-Data-Move-Utility/export.json

**Comment by hknokh** [comment]
Hello, @kowszymon 
Thank you for the reaching me out, but in future, I woluld ask you to follow the guidelines for ticket opening which are described in the readme.
---
Please, attach also the latest log and the dump of the _target.csv files containing errors to see what is happening on your side. And the attached link is broken, please resend all the required information.
Thanks.

**Comment by kowszymon** [comment]
Hi,

I'm sorry, I will follow the instructions next time. Apparently json format is not supported.


[Export json and target.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5672416/Export.json.and.target.zip)

**Comment by hknokh** [comment]
Hello @kowszymon 

Sorry for the late replay! 

I have a couple of questions.

- What does it exaclty mean "heap size error" ? Its on the side of salesforce or it's a plugin memory issue ?
If you are on the developer edition maybe you realy have no anough room for the rest records even on the second run.

- Why in your export.json the Account object  is excluded in your script ? 
It may prevent the ivybase__Store__c to be populated correctly since necessary account records could be missing in the target env. 

- Regarding the duplicated value error.
It can occur due to the tool also including externalid field in the update, so in your case on the second run, it is trying to update all existing records, including the field marked as external id in the salesforce, and it's  not allowed since such value already exists even it is the same record. 
So for now, if you are using fields of type "external id", you need to delete target records before, not to do an Upsert or Update. May be it sounds like workarround by that is.  I am thinkling about the solution for it and it will come further.

- Regarding the REQUIRED_FIELD_MISSING.
Because the Rote records were failed so there is no parent records for the RouteDetails to populate the lookups.

**Comment by kowszymon** [comment]
Hello Haim,

The heap size error is a result of a lot of automations on Accounts that
are on triggers from a managed package which is unavailable to me. I need
to move 17800 Accounts and after 4 upserts it is done correctly. BTW have
you thought of implementing a possibility to reduce batch size so the
problem doesn't occur like it is done when importing via Data Loader?

Generally the case is that at first I upsert only Accounts 4 times so
finally it is done successfully without heap size error, then I exclude it
and upsert the rest of objects. The rest of objects is imported
successfully including 60 Route records but excluding Route Details which
of there are ca. 12 000. Part of them fails due to inability to obtain
individual access and a part of them due to the same heap size error from
AccountTrigger. This is why I want to upsert them again, so the missing
ones are imported. But then the Route and Store (Account Lookup) fields are
empty. Is there a way to import only Route Details and assign them to
existing Accounts and Routes?

Deleting the target records first is not going to work due to the heap size
error. The external Id that I created is making sure that there are no
duplicates and it is fine when the upsert fails due to these duplicates,
but I need a way to assign Route Details to existing Accounts and Routes.
What do you suggest? To do upsert without specifying external Id?

wt., 15 gru 2020 o 15:55 Haim Knokh <notifications@github.com> napisał(a):

**Comment by hknokh** [comment]
Hello, 
find the answers below:

- **"Have you thought of implementing a possibility to reduce batch size so the
problem doesn't occur like it is done when importing via Data Loader?"**
Yes, you already have the option for limit the batch size: bulkApiV1BatchSize. 
Also put bulkApiVersion="1.0" to use V1.
Refer:
https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format

- **"Is there a way to import only Route Details and assign them to
existing Accounts and Routes?"**
Yes, just **don't put the account and route to excluded=true**, instead put the operation="Readonly" for them, so it will use the existing target records to update child lookups of the rest of the objects in the script. Otherwise these objects will be marked as **unusable** and **it will entirely skip them from the processing**.  
Generally, never use **excluded=true** if you want to update child records in the second run (BTW maybe this is your issue here).
Indeed excluded=true is intended only for cases when you don't need to run those objects **at all**

- **"What do you suggest? To do upsert without specifying external Id?"**
Try the solution above and let me know what is happening.
