### ISSUE TITLE
[QUESTION] - Clarification for Files migration

### ISSUE THREAD

**Issue by VFansss** [forcedotcom/SFDX-Data-Move-Utility#244]
Hi!

Before everything: thanks for your work! The plugin rocks, and my teams and I use it very often and happily.

Migration of records is working good, but I'm having some issue to understand if,and eventually how, the migration of File and Attachments works.

Because in the Help center I read that [files and content document are not supported](https://help.sfdmu.com/faq/import-of-binary-data/can-i-migrate-salesforce-files-and-content-documents) but then on [THIS](https://help.sfdmu.com/full-documentation/advanced-features/export-attachments-and-files) page I can see a tutorial on how to make them working.

Thus, I guess that actually Files are supported.

Still, I've tried it but without succeeding.

I've tried a LOT of various combination of things, but I didn't exported anything.

This is my export.json:

![immagine](https://user-images.githubusercontent.com/15073502/101926019-eb319c00-3bd2-11eb-9045-e5244187e071.png)

Is basically taken straight from your documentation.

I've loaded an image on the Account:

![immagine](https://user-images.githubusercontent.com/15073502/101925893-b7567680-3bd2-11eb-98de-d6ab944ab041.png)

and run the script, but my export doesn't have

''''
sfdx sfdmu:run --sourceusername MY_ORG --targetusername csvfile --path data/attachments_export  --filelog --verbose
''''

At the end, the resulting .csv export my Accounts but the ContentVersion .csv is empty.

My questions are:

* Are Files actually supported?
* Is only needed to put, inside export.json, the ContentVersion object definition and no other information?
* How to make it working with other objects, aside Account?

On the documentation, I can read:
 
>  for example to migrate Attachments, related to the Cases, use ParentId$Case

I understand the **$Case** part, but how to find what I should have to write before the $?

Thanks for reading.
keep up the good work

**Comment by hknokh** [comment]
Hello @VFansss 
First, thank you for the positive feedback, really appreciate that!

----
Yes, the file migration is supported, I forgot about the old article saying that it's not supported, need to update the documentation.
But let say it's only partialy suppored, because we can transfer Note, Attachshments, but regarding the Files only direct relationship is supported which says you can transfer content versions directly attached to the specific record via FirstPublishLocationId lookup. But for the content versions attached to multiple parent records using ContentDocumentLink - is'not supported yet.

----
Regarding you case and the configuration.
In you screenshots you want to transfer files attached to Product (maybe the sobject is Product2?) but why in your export json file you are writing FirstPublishLocationId$Account ? The part after $ should be the **name of the sobject** that you want to link to it the FirstPublishLocationId lookup since the FirstPublishLocationId a **polymorphic** field.

And also in your script, becides the Account object, you probably need to include the definition to transfer the parent Product records that the Plugin can then attach the Files to them? 

Or if you are not including it - make sure that the product records with the same Names (Name is the default externalid if you ommit the object definition) exist in both the source and the target env, otherwise the Plugin will not find the records where to attach the Files in the target, since it does compare between the source and the target records by the given external id.

Note, that the Plugin WILL NOT TRASNFER product records because the object is not included in the script and so that by default will use ReadOnly operation for the product sobject.

---
Conclusion. 
Really I can't give you the actual solution like let you do that an that, because you have to analyse the case on your side and it's depend on variety of things. But I hope now at least you have the way to move ahead from the place you stuck there...
