### ISSUE TITLE
[QUESTION] - Hierarchy Level Limit?

### ISSUE THREAD

**Issue by mikesimps** [forcedotcom/SFDX-Data-Move-Utility#245]
First of all, thank you for building this, it's pretty awesome!

- Ask your question or what kind of help you need.
Is there a limit on the number of levels/relationships the tool will navigate?

For example, I have a config that tries to retrieve the following objects:
- Pricebook2
- PricebookEntry
- Product2
- SBQQ__ProductFeature__c
- SBQQ__ProductOption__c

Ideally, I would like to be able to just filter the pricebook I want and have it bring back all "deep" children of these objects. Right now, it appears to be limited to just a few levels. If I make Pricebook2 the master, it brings back PricebookEntry and Product2 just fine, but skips over the Product Features and Options. However, if I set the Pricebook2 and Product2 as the master (and filter on specific Product2) I can get all the related feature and option records as expected.

Is this a known limitation or is it possible I may need to configure something extra to get what I need?

**Comment by hknokh** [comment]
Hello @mikesimps 
Thank you for the positive feedback about my Plugin!

Regarding your question, basically there is no limit for the child levels.
It's correct to  set the top most parent object to master=true and apply filter to its records and the other children to set to master=false. This config should indeed retrieve the entire child tree for the filtered master records.

So, for example for this data lookup model:
ProductFeature, Product options -> product2 -> pricebook2 
=> you can put to master=true just pricebook2.

Anyway, I have to see your full **export.json** + full latest **.log** files to correctly qualify the case.

**Comment by mikesimps** [comment]
Here is the export.json and log file from the latest run where Pricebook is the master (how I would expect to run it). I had to replace some info in the log to protect the source, but it should not hinder any analysis. Pricebook, Product, and Pricebook Entry numbers are all correct/expected.

[Pricebook master - export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5690762/export.json.txt)
[Pricebook master.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5690766/2020-12-14__13_08_02.log)

Thanks for your help!

**Comment by hknokh** [comment]
Hello, @mikesimps 

I didn't see lookup from SBQQ__ProductFeature__c and from SBQQ__ProductOption__c to product2 and/or to Pricebook2
Can you mention the key lookups fields of each sobject in your data model, I would like to understand the relathioships ? Maybe something is missing ?

The issue can be that it can't find the exactly intersection between multiple sobjects pointing to the same parent sobject, ie. you are filtering the pricebook2 with single record, it's finding the products2 related to this record, then it tries to locate SBQQ__ProductFeature__c that pointing both to pricebook2 record and to product2 records, and maybe there is no such SBQQ__ProductFeature__c records that matching these limitations. Maybe a lot of such cases that is why when you are putting pricebook2 and product2 to master it locates more records because it has less limitations to find the intersections between records.

**Comment by mikesimps** [comment]
Yeah the CPQ data model is not always straight forward. Lookups for each below:

**SBQQ__ProductFeature__c**
SBQQ__ConfiguredSKU__c [*Product2]

**SBQQ__ProductOption__c**
SBQQ__ConfiguredSKU__c [*Product2]
SBQQ__Feature__c [*SBQQ__ProductFeature__c]
SBQQ__OptionalSKU__c [*Product2]

I think I understand what you are saying, but I can't comprehend of why filtering on the specific product ID would behave differently than using the product ID derived from the list of pricebook entries. If you have any hints/instructions on where I could check in the code, I can try running in debug mode to troubleshoot.

**Comment by hknokh** [comment]
Ok, Not sure. 
Ok, Not sure.  Normally no problem to retrieve such data model.  Need to debug to see how the data is changing at each steps. 
Generally all records per object are being processed in the migrationJobTask.ts The data is retireved in retrieveRecords() and updated in updateRecords() 
Because it proceeds with each object several times, so all migration process is consolidated in the migrationJob.ts (retrieveRecordsAsync(), updateRecordsAsync() respectively) 
Thanks in advance for the troubleshooting.
