### ISSUE TITLE
MissingParentRecordsReport - external ids

### ISSUE THREAD

**Issue by gidglass** [forcedotcom/SFDX-Data-Move-Utility#27]
It seems like the external id isn't being respected since its being logged as the Name field in the csv as opposed to the composite one specified in the export json? Please see below:

export.json:
```
{
    "objects": [
        {
            "query": "SELECT Id, readonly_false FROM Targeting_Category__c",
            "operation": "Upsert",
            "externalId": "Category__r.Name__c;Name__c;JSONName__c;Date_Label_1__c;Date_Label_2__c;Number_Label_1__c;Number_Label_2__c;Picklist_Label_1__c;Picklist_Label_2__c;Text_Label_1__c"
        },
        {
            "query": "SELECT Id, readonly_false FROM Hierarchy__c",
            "operation": "Upsert",
            "externalId": "Code__c;GUID__c"
        }
    ]
}
```

MissingParentRecordsReport:
```
Date update,Id,Child ExternalId,Child lookup,Child SObject,Missing value,Parent ExternalId,Parent SObject
2020-05-19  16:08:06.332,a0Nc00000085w0nEAA,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-17027,Name,Hierarchy__c
2020-05-19  16:08:06.334,a0Nc00000085vyNEAQ,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-17027,Name,Hierarchy__c
2020-05-19  16:08:06.334,a0Nc00000085vyQEAQ,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-17027,Name,Hierarchy__c
2020-05-19  16:08:06.334,a0Nc00000085vyiEAA,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-33314,Name,Hierarchy__c
2020-05-19  16:08:06.334,a0Nc00000085vyjEAA,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-23000,Name,Hierarchy__c
```

All self-referencing records are inserted correctly, but the relationship between these two objects are not being populated. 

Here's the basic data model as an fyi:

**Object_1__c** (Hierarchy__c in the above exports.json)
- Has optional self-referencing lookup to itself
- Uses a composite external id composed of multiple fields on Object_1__c

**Object_2__c** (Targeting_Category__c in the above exports.json)
- Has optional self-referencing lookup to itself
- Had optional lookup to Object_1__c
- Uses a composite external id composed of multiple fields on Object_1__c and Object_2__c

**Comment by gidglass** [comment]
@hknokh - whats more bizarre, if I flip the order of the objects in the exports json, it entirely ignores the second object...
```
{
    "objects": [
        {
            "query": "SELECT Id, readonly_false FROM Hierarchy__c",
            "operation": "Upsert",
            "externalId": "Code__c;GUID__c"
        },
        {
            "query": "SELECT Id, readonly_false FROM Targeting_Category__c",
            "operation": "Upsert",
            "externalId": "Category__r.Name__c;Name__c;JSONName__c;Date_Label_1__c;Date_Label_2__c;Number_Label_1__c;Number_Label_2__c;Picklist_Label_1__c;Picklist_Label_2__c;Text_Label_1__c"
        }
    ]
}
``` 

Not sure if these are related bugs 🤷‍♂️

**Comment by hknokh** [comment]
Hello @gidglass 

It is really strange and I agree that it is annoying. But.... unfortunatelly I still can't reproduce your error on my local machine. 
For me it always works perfectly at the very similar data model and with a composite external ids in both objects. In this case I would say let me see what happens on you machine, how you run the plugin, in which environment: which version of the plugin, npm, nodejs, salesforcedx, etc. you are using, because such kind of issues could depend on very large amount of circumstances, and not always it's a software bug.

I am sharing you the info about my environment that the Plugin is running correctly:
$ sfdx sfdmu:run --version
Plugin version: sfdmu v2.8.324

$ npm --version
6.14.4

$ node --version
v10.15.1

$ sfdx --version
sfdx-cli/7.53.0-839fc82926 win32-x64 node-v10.15.3

$sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.8.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.8.0 (core)
└─ salesforce-alm 48.8.0 (core)
sfdmu 2.8.324 (link) D:\XXXXXXXXXX\SFDMU-Data-Move-Utility
sfdx-cli 7.53.0 (core)
Please recheck yours, maybe reinstall components, for now, I can't provide you the best solution, since can't reproduce the issue.

**Comment by gidglass** [comment]
@hknokh I debugged a bit and seems to be this line that is throwing things out of whack for me.

`script.ts` on line 122:

```
this.objects = Common.distinctArray(this.objects, "name");
```

Seems like the "name" property for both my objects are being set to blank:

```
ScriptObject {
  mockFields: [],
  query: 'SELECT Id, readonly_false FROM Targeting_Category__c',
  deleteQuery: '',
  operation: 'Upsert',
  externalId:
'Category__r.Name__c;Name__c;JSONName__c;Date_Label_1__c;Date_Label_2__c;Number_Label_1__c;Number_Label_2__c;Picklist_Label_1__c;Picklist_Label_2__c;Text_Label_1__c',
  deleteOldData: false,
  updateWithMockData: false,
  mockCSVData: false,
  targetRecordsFilter: '',
  excluded: false,
  useCSVValuesMapping: false,
  allRecords: true,
  excludedFields: [],
  name: '',
  originalExternalId: '',
  isExtraObject: false,
  processAllSource: false,
  processAllTarget: false }
ScriptObject {
  mockFields: [],
  query: 'SELECT Id, readonly_false FROM Hierarchy__c',
  deleteQuery: '',
  operation: 'Upsert',
  externalId: 'Code__c;GUID__c',
  deleteOldData: false,
  updateWithMockData: false,
  mockCSVData: false,
  targetRecordsFilter: '',
  excluded: false,
  useCSVValuesMapping: false,
  allRecords: true,
  excludedFields: [],
  name: '',
  originalExternalId: '',
  isExtraObject: false,
  processAllSource: false,
  processAllTarget: false }
```

Trying to trace where that property is supposed to get set.

Very much appreciate your help - I'll keep digging around!

**Comment by hknokh** [comment]
@gidglass 
Thank you for your help with debugging!
I will check your finding ASAP.

**Comment by hknokh** [comment]
Hi @gidglass 
Thank you for your help, friend! 
I checked your solution, but can't resolve the issue by this way, cause putting  the distinct filter AFTER setting up the script objects which might be sometimes duplicated - will cause some side effects. 
Hence have fixed the issue in different kind - by reverting the name property to getter leaving the filter in the same place.  
Please update the plugin to the latest version and retry to migrate.

**Comment by gidglass** [comment]
@hknokh - thanks again for your help! Was fun debugging - I pulled the latest changes and things seem to be working smoothly so far! Will keep you posted if I find any other bugs 🤣 Cheers!
