### ISSUE TITLE
Importing RecordTypes With Different Namespaces

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#293]
If I have Account records where I want to go from source to target as below, I'm not clear how I'd do that. I  don't need to add the RecordType because it's already in the org. It would normally be a mapping but these are RecordTypeIds

```
Source: Account.RecordType = ns1__Value1
Target: Account.RecordType = ns2__Value1
```
Just adding RecordTypeId in SOQL doesn't work since the namespaces are different

**Comment by hknokh** [comment]
Hello @veaux 
Unfortunatelly the Tool has nbo option for the RT namespace mapping.
Normally it handles RT namespaces as well, but the Source and the Taget namespaces should be teh same
https://help.sfdmu.com/full-documentation/advanced-features/handling-record-type
***
Since your question has been aswered, I'm closing the case for the current moment.
Feel free to reopen if your you have any additional questions.
