### ISSUE TITLE
[QUESTION] - Using sfdmu as part of the development process. Is it possible?

### ISSUE THREAD

**Issue by Raspikabek** [forcedotcom/SFDX-Data-Move-Utility#310]
Hi there! So I'm trying to use sfdmu plugin as part of the development process of my team. The idea basically is:

Let's say we've a couple of record oriented configurations (like CPQ does), where you have a bunch of objects related between each other. I'm trying to open the possibility to the team to update their Sandboxes/Scratch orgs based on the information stored in csv files in the repository + let them add additional config/data sample records by retrieving information after they've done some operations in their orgs (for those new features or new objects that required additional data)

I'm building a few easy scripts in my package.json to execute this commands easily, so all devs can do exactly the same.

**What do I want to achieve?**

Let's imagine we want to have sample config data for everybody:  CustomObject1__c  & CustomObject2__c (2 has a master detail to 1)

I'm trying to build 2 commands, a retrieve and a push information:

retrieve will execute `sfdx sfdmu --sourceusername mydefaultorg --targetusername csvfile -p sfdmu-config`
push will execute: `sfdx sfdmu --sourceusername csvfile --targetusername mydefaultorg -p sfdmu-config`

Here my sfdmu `export.json` file:

```
{
    "excludeIdsFromCSVFiles": true,
    "importCSVFilesAsIs": false,
    "objects": [
        {
            "query": "SELECT Name, Date_Field__c, Text_Field__c, External_Id__c FROM CustomObject1__c ORDER BY External_Id__c  ASC",
            "operation": "Upsert",
            "externalId": "External_Id__c",
        },
        {
            "query": "SELECT Name, Date_Field__c, Text_Field__c, External_Id__c, CustomObject1__c FROM CustomObject2__c ORDER BY External_Id__c  ASC",
            "operation": "Upsert",
            "externalId": "External_Id__c",
        }
    ]
}

```
When I retrieve information it is fine. Actually, the CSV file for CustomObject2 create the header: `CustomObject1__r.External_Id__c` correctly.

Now... I'm struggleing in the import part, when I try to reuse this same exported CSV as --sourceusername and targeting my dev org, the error described in CSVIssuesReport is that the column `CustomObject1__c` is missing in the file.

If I set temporarily `importCSVFilesAsIs` as `true`  the process continues but the lookup field is not populated

Wonder if I'm missing something of this specific flow is not one of the use cases for this plugin.

Thanks in advance!

**Comment by Raspikabek** [comment]
After further testing, I've achieved to execute my process by setting `excludeIdsFromCSVFiles` as `false`, this seems to work fine, due to all columns are populated correctly, however seems like the plugin depends on the Id fields to do the internal matching. Is this right?

This should of no use in my use case, due to if I leave ids in the repository files, these ids will change every time anyone retrieves a new elements from their environment, displaying that the whole file has been updated + new additional lines.

Is there any way to use --sourceusername csvfile with a csv that does not contain `ids` and only contains `external id` fields as references?

**Comment by hknokh** [comment]
Hello @Raspikabek 

The answer for your last question is yes, you can use your files previously generated by the Plugin with the option excludeIdsFromCSVFiles = true to import from csv file into org. The matching between objects is done by the external id field not by the record id.  During the import the tool virtually "corrects" the csv files by generating temporary record ids based on the provided external id values.

Regarding the mssing column - disregard this message, it is just the warning during the csv validation.
If your CustomObject2__c.csv contains CustomObject1__r.External_Id__c  it should import CustomObject2__c and populate CustomObject1__c  despite this warning.

But make sure that your files built correctly and values in the column CustomObject2__c -> CustomObject1__r.External_Id__c are matching the values of the column CustomObject1__c -> External_Id__c.csv

Don't set importCSVFilesAsIs = true with excludeIdsFromCSVFiles=true  because these are contradictory props and they will interfere each with other.

**Comment by hknokh** [comment]
***
Looks like your question is answered and we are closing the case for the current moment.
Feel free to reopen if you will have amy additional questions.
