### ISSUE TITLE
[ERROR] Error during execution of the command: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>.e

### ISSUE THREAD

**Issue by perseveregary** [forcedotcom/SFDX-Data-Move-Utility#331]
**Describe the bug**
Using the attached export.json to run the migration job and received Bad Message 414. URI Too Long. 

**To Reproduce**
Run the migration job with attached export.json

**Expected behavior**
No Error

**export.json**
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6875670/export.json.txt)

**Log file**
Attach your full **[2021-07-26__14_46_08.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6875674/2021-07-26__14_46_08.log)

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment]
Hello @perseveregary 
The  Plugin always controls internally the size of the queries costructed at the runtime to prevent the limitation issues. 
For example it controls the lenght of the WHERE clause (4000 characters) as described there:
https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_soslsoql.htm
However because you're using all multiselect word, seems that the final number of the fields in the query of Product_Custom__c is extremelly large and this causes the error. 
May be you could try to use **updateable_true** instead of **all**, this will reduce amount of the fields in the final query by including only the updatable fields.
For more details:
https://help.sfdmu.com/full-documentation/advanced-features/field-multiselect

**Comment by perseveregary** [comment]
> Hello @perseveregary
> The Plugin always controls internally the size of the queries costructed at the runtime to prevent the limitation issues.
> For example it controls the lenght of the WHERE clause (4000 characters) as described there:
> https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_soslsoql.htm
> However because you're using all multiselect word, seems that the final number of the fields in the query of Product_Custom__c is extremelly large and this causes the error.
> May be you could try to use **updateable_true** instead of **all**, this will reduce amount of the fields in the final query by including only the updatable fields.
> For more details:
> https://help.sfdmu.com/full-documentation/advanced-features/field-multiselect

@hknokh - thanks for getting back . really appreciate your work on this tool and spending your valuable time on this and helping thousands of admins and devs across the globe.
