### ISSUE TITLE
Different behavior for the command - sfdx plugins:link

### ISSUE THREAD

**Issue by kishanSFDC1999** [forcedotcom/SFDX-Data-Move-Utility#341]
I am getting different results when i try sfdx plugins:link command!

Sometimes its like 
![jjja](https://user-images.githubusercontent.com/29170586/131850597-c159d7d7-5223-4d9b-bb0e-81487824c632.png)
When above, everything is working fine.

While, sometimes its like:
![image](https://user-images.githubusercontent.com/29170586/131850799-045e6306-501b-4989-bdaa-632658de03dd.png)
No command works when the the repo is linked this way!

Its in priority. Can i know the reason why separate logs are generated for each different time and how to solve?

**Comment by hknokh** [comment]
Hello, 
The second one is incorrect. I guess, you already have the plugin installed globally using sfdx plugins:install sfdmu
and then you are trying to link it also using the git source.
I think that the both installations can't woking together because it's the same plugin unit.
Give a try  to firstly run the both uninstall commands:  **sfdx plugins:uninstall sfdmu** and **sfdx plugin:unllink**
Then re-link the plugin  clone again.
Hope it will help

**Comment by hknokh** [comment]
We hope, that your issue is already successfully resolved and we are closing this case for the current moment. 
However, feel free to ask for the additional help.
Thanks.
