### ISSUE TITLE
[BUG]-Unable to migrate Account with mixed business/person account

### ISSUE THREAD

**Issue by myellon7** [forcedotcom/SFDX-Data-Move-Utility#378]
The documentation shows that tool offers full support for person accounts and can handle loads with mixed person accounts and business accounts. we are finding that with mixed person accounts, it does not work, because though two CSVs are generated (one for person account, one for business account), it does not split out the fields based on whether applicable to person or business account so we see an error such as: "Account: bad field names on insert/update call: MiddleName"

export.json as follows:

{
    "objects": [
        {
            "query": "SELECT standard_true FROM Account WHERE Id IN ('0017d0000131cvfAAA','0017d0000131dH2AAI')",
            "operation": "Insert",
            "useValuesMapping": true,
            "externalId" : "Name"
        }
    ]
}

attaching relevant files
[ValueMapping.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7487681/ValueMapping.csv)
[2021-11-05__09_43_07.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7487684/2021-11-05__09_43_07.log)
[Account_insert_person_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7487686/Account_insert_person_target.csv)
[Account_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7487687/Account_insert_target.csv)

**Comment by hknokh** [comment]
Hello!
Sorry for the delay in the response.
The issue seems to be due to the following point:
https://help.salesforce.com/s/articleView?id=000332623&type=1
I guess that the Allow Customizable Person Names feature is on in your orgs.
I fixed the issue by removing extra fields like MiddleName, Suffix from being processing for business accounts, leaving them intact for the person acconts.

I have no option to check this, since have no playground with person accounts having Allow Customizable Person Names on.
So please check the fix on your side and let me know.

Thanks.

**Comment by hknokh** [comment]
For
