### ISSUE TITLE
[BUG]-Composite external id failure

### ISSUE THREAD

**Issue by alinmocanuwork** [forcedotcom/SFDX-Data-Move-Utility#389]
**Describe the bug**
When using multiple external ids in one field, I see an error on that step.

**To Reproduce**
Describe steps to reproduce the behavior.
"externalId":"Account__r.AgencyId__c;Type__c",

**Expected behavior**

**export.json**
Attach your **export.json** file
{
			"query":"SELECT all FROM PaymentOverride__c",
			"operation":"Update",
			"externalId":"Account__r.AgencyId__c;Type__c",
			"deleteOldData": false
},

**Log file**
Attach your full **.log** file.

{PaymentOverride__c} Retrieving the SOURCE data from Org (STAGE 1: all records) ...
Command in progress ...... done
[ERROR] Error during execution of the command: line 1:224 mismatched input ';' expecting FROM.
Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).
Total time elapsed: 00h 03m 10s 703ms .

I don't have access to send the complete files

**Comment by alinmocanuwork** [comment]
[export.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7674977/export.zip)
 I got the full file

**Comment by hknokh** [comment]
Hello
I saw your export.json.
Very sorry, but can't assist you with your issue because the configuration is very complex and your are using all keywords, can be a lot of circumstances there. Need to debug directly on your end with the live source/target envs.

**Comment by hamish-buckley-trineo** [comment]
@alinmocanuwork, you have used a colon instead of a semi colon in your externalId

It needs to be:
"externalId";"Account__r.AgencyId__c;Type__c",

**Comment by hknokh** [comment]
@hamish-buckley-trineo
It is correct to put a colon there, because it's a json property separator, not a part of the externalid itself. This seems not to he the real issue with this configuration...
btw. @alinmocanuwork  In your excludedFields you are sometimes putting fields in wrong case for example Quotes__C instead of Quotes__c. It will not work.

**Comment by alinmocanuwork** [comment]
It's weird that I used the same format in the past and it was working. Similar, record type has composite external id and it's working. Any settings in the sandbox that I am missing? The fields are there for sure. If I remove this object, others are working fine. It started retrieving, but when trying to retrieve this data, it fails

Check this full log, maybe it helps?
[2021-12-07__17_12_40.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7712636/2021-12-07__17_12_40.log)
.

**Comment by hknokh** [comment]
@alinmocanuwork , 
thanks for attaching the log.
It's really weird. 
I see that it does not resolve the complex external id and attempts to use Account__r.Agencyid__c;Type__c instead of $$Account__r.Agencyid__c$Type__c. Moreover it includes this field twice in the query... 
The problem is that I can't reproduce it here and all of my checks are done in a blind mode. 
May be you can provide me the access to your orgs to debug it on your side ? 
I can try to go on it.

**Comment by alinmocanuwork** [comment]
How can we schedule a meeting or talk in private? Can you send an email to alinmocanuwork@gmail.com and we can talk on Monday?

**Comment by alinmocanuwork** [comment]
Is this because I use Update instead of Upsert? Maybe?

**Comment by hknokh** [comment]
Yes we can talk in private. 
I've replied  you from my  mailbox.

**Comment by hknokh** [comment]
Hello @alinmocanuwork 
Should be working now.
Tested on your sandbox.
