### ISSUE TITLE
[QUESTION] - Is there an issue with a comment on "forwards" and "backwards" processing?

### ISSUE THREAD

**Issue by ethanmichel0** [forcedotcom/SFDX-Data-Move-Utility#413]
Hey! I am a little confused on the "reversed" query mode and am wondering if there is a mistake in one of the comments, or if I am just confused. On SFDX-Data-Move-Utility/src/modules/models/job_models/migrationJobTask.ts line 778 (see picture below) there are comments about the "reversed" mode along with "forwards" and "backwards" processing. It seems to me like the arrows underneath If reversed mode is false should have an arrow coming from the parent to the child instead of the child to the parent since the description of reversed = false states "queries from the parent related object to child object" . Am I correct in this error, or wondering if I am just not understanding the comments properly.

This is my understanding of how the query modes
<img width="876" alt="Screen Shot 2022-01-26 at 11 00 30 AM" src="https://user-images.githubusercontent.com/55289720/151200174-ce02219e-5653-48c7-88b9-355a9248ff4c.png">
 work, and I totally could be wrong! Could someone please let me know if this is correct? Thanks for your help!

**Comment by hknokh** [comment]
Hello @ethanmichel0 

I strongly would not suggest you to go deeply into my comments. Sometimes I am drunk when writing this, haha :) 
Seriously, all the comments for my own internal use to make me understand what I did.  In some cases my comments really help me, in other cases I have to look again on the code to remember what goes.

Regarding your question. 

Actually the Tool pulls records for each object several times to ensure that all relationships were correctly handled. Also there is difference between processing source and target records + master / child object + if the object has ​limitations in the query like WHERE, LIMIT. 
Not all data models actually need both 'backwards' and 'forwards' modes. Not all data models actually need 'reversed' queries. Even the Tool tries to query records in all possible modes, it is still not necessary that the query will return new records each time.

In short:

'forwards'   retrieves all non-lookup fields + all lookup fields on the child object when the parent task is BEFORE the child one within the current migration job and these parent records were already retrieved in previous steps. The child records  are getting queried using "WHERE ParentLookup__c IN [Parent Record IDs]"

'backwards' retrieves  all lookup fields on the child object when the parent task is AFTER the child one within the current migration job. This mode can be performed only after the parent records were already retrieved using 'forwards' mode. The child records are also getting queried using "WHERE ParentLookup__c IN [Parent Record IDs]"

'reversed' is the additional query mode, meaning "please get me ALL child records which are filtered by ALL parent records'. Reversed mode collects all parent ids from all objects and puts they to WHERE IN of the child object to retrieve the additional child records.

Why it called 'reversed' ? Don't remember why I called it so. Maybethis name is because it selects 'parent' objects which have both parent and child lookup fields to other 'child' objects (like a circular references),

I will think. about to change the name from 'reversed' to something more informative...)
