### ISSUE TITLE
[FEATURE REQUEST] - Provide more details in skipped records

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/SFDX-Data-Move-Utility#416]
Today SFDMU provides this message when there are skipped lines

![image](https://user-images.githubusercontent.com/17500430/151526781-50ed1a73-5f75-42a4-a593-96a9f606a7b0.png)

It would be easier to investigate issues if we could have:
- The number of skipped items because the data is the same
- The number of skipped because no matching was found between source & target

Thanks :)

@hknokh in addition, it would be great to know the number of inserted items + the number of updated items here :)

![image](https://user-images.githubusercontent.com/17500430/151980914-b6e4fc2b-13e7-4208-8639-3ee66db18836.png)

**Comment by hknokh** [comment]
Hello @nvuillam 
There is some implementation problems to show number of inserts/updates separately.
Anyway I will try to implement this ASAP since it's useful feature.
Thanks for idea.

**Comment by hknokh** [comment]
Hello @nvuillam,

Thank you again for this suggestion.

This feature request is now implemented.

What was added for your exact request:
- The skipped-record warning is now split by reason.
- It now reports how many were skipped because data is the same.
- It now reports how many were skipped because no matching target record was found.
- It also reports other skipped reasons when applicable.

About your additional note on inserted and updated counts:
- Per-pass summary already reports Updated, Deleted, and Inserted counts.

Please, see also the doc articles:
- [The Execution Log](https://help.sfdmu.com/full-documentation/reports/the-execution-log#skipped-records-reason-breakdown)
- [Run Command Flags](https://help.sfdmu.com/full-documentation/reports/run-command-flags#diagnostic)

Best regards
