### ISSUE TITLE
[BUG]-BULK Upsert operation is changed to insert

### ISSUE THREAD

**Issue by hubsonx** [forcedotcom/SFDX-Data-Move-Utility#417]
**Describe the bug**
I want to set up basic upsert operation of records matching on externalId field. I am forcing the bulk API to be able to see the operation that the plugin is trying to perform. It always executes the Import operaton regardless of Upsert on OldId__c that I'm trying to perform.

**To Reproduce**
1. Create OldId__c (Text, 18 chars, extId, unique) in both Source and Target Orgs.
2. Execute the plugin (v 4.12.6) through sfdx

**Expected behavior**
Upsert Operation being visible in Bulk Load Data Jobs in SF (using OldId__c as External Id). Records being consistently upserted in target org.

**Comment by hknokh** [comment]
Hello @hubsonx 
It's correct behavior.
The Tool never uses the native SF Upsert bulk jobs neither in V1 nor in V2 version fo API. 
The reason because the native Upsert operation is extremely limited stuff and can't serve all features which the SFDMU supports.
The Tool creates Insert bulk jobs for the new records and Update for those which should be updated.
It iternaly decides which records should be inserted or updated. Upsert operaton is a mix between Insert and Update jobs. You should not worry about this if the data is correctly migrated at the end of all.
