### ISSUE TITLE
Skip target updates with large datasets

### ISSUE THREAD

**Issue by grand-wazoo** [forcedotcom/SFDX-Data-Move-Utility#419]
I am trying to understand the logic behind skipped target updates. I do like that sfdmu skips matching records, but it seems to only work for small datasets or maybe the target number of records need to match the source as well? I got inconclusive results in my local testing. I need to push large datasets and sometimes sfdmu crashes because of CONNRESET/CONNREFUSED errors and then I have to start over again and it's taking forever...

When I push 5 records and set target query to pull 5 records, it skips (very good):

Total retrieved within all steps (source/target): 5/5 records.
[INFO] There are 5 skipped target updates, since no matching was found between the source and the target records by the given ExternalId key, or the data is the same.

But when I push 80K, it doesn't skip and does an update for all 80K records (undesirable).

Here I reproduced it by changing the query only - it pull 88K records and those 5 I am trying to push are among them (and were just skipped above), but this time it does an update:

Total retrieved within all steps (source/target): 5/88332 records.
Updating the Target has been completed. Processed 5 records.

I can't break down the files - there is a complex set of interdependencies and I need to push 20 objects in one run and the source files are generated by the pipeline (and the pipeline calls sfdmu as well).

**Comment by hknokh** [comment]
There is no a single answer for this question. 
It depends on the export.json configuration. 
In most of cases it queries the source then performs in the target WHERE Object__r.Name IN (SOURCEID_NAME, SOURCEID_NAME2, etc)
But sometimes in order to cover all object dependencies and to find all records which should be updated, it have to query all records then it filters them internally in the memory.
For example if you select **SELECT id from Object__c**  it will try to get all source records and all target records.

**Comment by grand-wazoo** [comment]
I think my question was lost in too much information provided. How does sfdmu decide whether the record should be skipped or not? I know for a fact (as described above) that a record I am upserting is identical to the one in salesforce. If I try to upsert that record only (or a small set of records, like 5), it will be skipped, but if it's part of a larger dataset and/or the query return a large dataset - sfdmu will execute an update, which is what I am trying to avoid.

**Comment by grand-wazoo** [comment]
External Ids are unique. I've verified it. When I run this query it always returns 5 records:
Select Id,CHS_Source_Id__c,DayOfWeek,EndTime,OperatingHoursId,StartTime,Type,X24_Hours__c FROM TimeSlot  Where CHS_Source_Id__c LIKE 'HOD TimeSlot1:1:%'
This is TimeSlot.csv I am importing (to test):
[TimeSlot.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7987210/TimeSlot.csv)

This export.json will skip them:

> {
>   "objects": [
>     {
>       "query": "Select Id, CHS_Source_Id__c, Account__c, Name, TimeZone, Type__c FROM OperatingHours  Where CHS_Source_Id__c !=''",
>       "operation": "Readonly",
>       "externalId": "CHS_Source_Id__c"
>     },
>     {
>       "query": "Select Id,CHS_Source_Id__c,DayOfWeek,EndTime,OperatingHoursId,StartTime,Type,X24_Hours__c FROM TimeSlot  Where CHS_Source_Id__c LIKE 'HOD TimeSlot1:1:%'",
>       "operation": "Upsert",
>       "externalId": "CHS_Source_Id__c"
>     }
>   ],
>   "promptOnMissingParentObjects": false,
>   "promptOnIssuesInCSVFiles": false,
>   "bulkApiVersion": "1.0",
>   "bulkApiV1BatchSize": 5000
> }


This will perform an update:

> {
>   "objects": [
>     {
>       "query": "Select Id, CHS_Source_Id__c, Account__c, Name, TimeZone, Type__c FROM OperatingHours  Where CHS_Source_Id__c !=''",
>       "operation": "Readonly",
>       "externalId": "CHS_Source_Id__c"
>     },
>     {
>       "query": "Select Id,CHS_Source_Id__c,DayOfWeek,EndTime,OperatingHoursId,StartTime,Type,X24_Hours__c FROM TimeSlot  Where CHS_Source_Id__c !='''",
>       "operation": "Upsert",
>       "externalId": "CHS_Source_Id__c"
>     }
>   ],
>   "promptOnMissingParentObjects": false,
>   "promptOnIssuesInCSVFiles": false,
>   "bulkApiVersion": "1.0",
>   "bulkApiV1BatchSize": 5000
> }

**Comment by hknokh** [comment]
Hello @grand-wazoo 
Thank you for the information provided. I will look on it ASAP.
In generaly we stopped supporting configuration/migration issues and I put a notificaiton about this. 
Anyway I will try myself to resolve yours as you opened it before.

**Comment by hknokh** [comment]
Hello.

Took a look on your issue again.

First of all, the details you provided here are incomplete and could not be investigated as is.

I can see idd the source records (in your TimeSlot.csv fle) but I still don't know which records are in your Target org are going to be compared for differences with the Source.  We need to see all 80K records )). I can say with 99.9% of warranty that it's issue with hashsum computing. 

Sumarrized, the answer to your main question: all the matching mechanizm is based on hashsum.

Since this issue is strictly depending on your data - it should be investigated only locally. 
I advise you to try debugging the SFDMU's source code for this. Sorry, but I can't provide you assistance in this.
