### ISSUE TITLE
[QUESTION] - How to handle multiple users with the same name?

### ISSUE THREAD

**Issue by jonny-harte** [forcedotcom/SFDX-Data-Move-Utility#436]
Hi, I am trying to import ServiceResources but they fail because I have 2 users with the same name. I've tried changing the externalId on User but that throws the below error. Is it possible to change the externalId on User?
```
ERROR at Row:1:Column:12
No such column 'CommunityNickname' on entity 'Group'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names..
```

```
{
  "apiVersion": "54.0",
  "objects": [
    {
      "query": "SELECT all, RelatedRecordId, OwnerId$User FROM ServiceResource WHERE Owner.Type = 'User'",
      "operation": "Upsert",
      "externalId": "Name"
    },
    {
      "query": "SELECT CommunityNickname FROM User",
      "operation": "Readonly",
      "externalId": "CommunityNickname"
    }
  ]
}
```

**Comment by hknokh** [comment]
Generally, it's possible to set externalID to another field for the User.

But the SFDMU does not treat user lookup fields (such as. OwnerId) as a polymorphic fields. It's something that specific to the current implementation.

Try as below (without using polymorphic syntax):

{
  "apiVersion": "54.0",
  "objects": [
    {
      "query": "SELECT all, RelatedRecordId, OwnerId FROM ServiceResource WHERE Owner.Type = 'User'",
      "operation": "Upsert",
      "externalId": "Name"
    },
    {
      "query": "SELECT CommunityNickname FROM User",
      "operation": "Readonly",
      "externalId": "CommunityNickname"
    }
  ]
}

**Comment by hknokh** [comment]
Hello
Hello @jonny-harte 

I've fixed this issue.

Please reinstall & retry.

I suggest to remove WHERE Owner.Type = 'User' from the query because it can cause issue of 'unknown field Owner.Type on entity User'

Use the script below without polymorphic fields:

{
"apiVersion": "54.0",
"objects": [
{
"query": "SELECT all, RelatedRecordId, OwnerId FROM ServiceResource",
"operation": "Upsert",
"externalId": "Name"
},
{
"query": "SELECT CommunityNickname FROM User",
"operation": "Readonly",
"externalId": "CommunityNickname"
}
]
}
