### ISSUE TITLE
[QUESTION] - Define parallelBulkJobs per scriptObject?

### ISSUE THREAD

**Issue by novumcoder** [forcedotcom/SFDX-Data-Move-Utility#442]
Heys guys,

i love this tool as it helps to setup our DEV sandboxes for a proper testing with real data coming from our productive ORG. Great work!

I have a little fight with the API limits. While trying to add 45k Accounts with a single job, it fails with the "Apex heap limit..." error. Im wondering why, i thought the Bulk API is chunking it automatically, but it looks its just too big with all the triggers and flows running.

So i added the "parallelBulkJobs" parameter globally setting it to 4, expecting it to chunk the 45k into 4 batches with round about 11k+ records each, but it is actually creating thousands of batches with just 4 records in it, which seems to be wrong.

So i put parallelBulkJobs=500 and it created multiple batches with 500 records each. Ok, but i can only set this globally, i want to set this only for Account while for others i need different batch sizes. 

Is that possible? If no, can you check if this is a viable feature to request?

**Comment by hknokh** [comment]
Hello @novumcoder 

Thank you a lot about your feedback!

I released the fix for the parallelBulkJobs / parallelRestJobs. It should now split the records correctly. If you set parallelBulkJobs = 4 it should create 4 jobs with 11K records per job as expected. Please, don't set it to 500 any more )

In addtion I've added the requested feature.
You can set the parallelBulkJobs / parallelRestJobs params both globally as before and per object in the relevant object section of the export.json. The object setting has always higher priority over the global one.

Please update the plugin and retry.

**Comment by novumcoder** [comment]
Wow, thanks for the quick response and patch. Will try out.
