### ISSUE TITLE
[QUESTION] - Question title

### ISSUE THREAD

**Issue by mrcdsouza** [forcedotcom/SFDX-Data-Move-Utility#447]
I am able to generate the configuration file via the GUI app with no errors. However, when I try to migrate data from object Location, I get the following error. The user has access to Location via Permission Set or Profile. I ran the Field Service setup too. What else should I check? Thanks

[ERROR] Mismatch org metadata error: Object Location is missing in the Target..

**Comment by hknokh** [comment]
Hello,

Apologies for the delayed response—your question was inadvertently overlooked. It seems the issue may be due to an outdated API version set by default in SFDMU, which does not support the object you are trying to migrate. Please consider upgrading SFDMU as it now supports the latest Salesforce API.

Regards.
