### ISSUE TITLE
How is the allOrNone flag supposed to work?

### ISSUE THREAD

**Issue by jeffreyazevedo** [forcedotcom/SFDX-Data-Move-Utility#465]
I'm curious what the behavior of setting allOrNone to TRUE in the export.json is supposed to be. My expectation was that it should cause the entire process to fail and stop if any single record insert fails, however I'm not experiencing that in my testing (there's a WARN in the log, but the entire process continues on and exits with a SUCCESS).

**Comment by yahirah** [comment]
It works per object per particular run, so if you import Accounts & Opportunities it will separately run transaction Account & Opportunities, and if 1 Account fails, the whole run fails, but Opportunities try to be imported.
Also, if you import 2000 Accounts and it is divided into 10 runs by 100 records, each run fails separately (e.g. 2 runs may fail because of two records, but 18 other runs will succeed).

**Comment by hknokh** [comment]
Thanks @yahirah

**Comment by jeffreyazevedo** [comment]
Thanks for clarifying! I will say that your explanation differs somewhat from what's listed in your documentation:
https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format
> Abort job execution on any failed record or continue working anyway.
If true the execution will stop or the user will be prompted to stop depend on promptOnUpdateError parameter.

This seems to imply that the execution of the process will stop, however according to your answer only the single object job will fail and everything else will continue on. Even with the promptOnUpdateError set to true, I'm not getting a prompt when some records fail.
