### ISSUE TITLE
[QUESTION]-Composite externalId is not being generated when --sourceusername is csvfile

### ISSUE THREAD

**Issue by kdoruibin** [forcedotcom/SFDX-Data-Move-Utility#483]
**Describe the bug**
Based on the comments in #452 I would expect that composite external Ids should be automatically generated when the source is a csv file. However, composite externalId is not being automatically generated when `--sourceusername` is a csv file. This causes sfdmu to insert duplicates instead of updating existing records when upserting records.

**To Reproduce**
Add a simple source csv file e.g. `L_TimeEntryCode__c.csv` to the same folder as the export.json file:
```
Name,L_Type__c,L_Value__c,L_SalesOrganisation__c,L_IsDefaultValue__c
"Alberta, US",Premium Number,AB,All,FALSE
"Alaska, US",Premium Number,AK,All,FALSE,All
"Alabama, US",Premium Number,AL,All,FALSE
```

**Expected behavior**
Records should be updated if matching records are found in the target org based on their composite external id.

**export.json**
```
{
    "objects": [
        {
            "query": "SELECT Id,Name,L_Type__c,L_Value__c,L_SalesOrganisation__c,L_IsDefaultValue__c FROM L_TimeEntryCode__c",
            "operation": "Upsert",
            "externalId": "L_SalesOrganisation__c;L_Type__c;L_Value__c"
        }
    ],
    "simulationMode": false
}
```

**Comment by hknokh** [comment]
Hi

Unfortunatelly this is not how the Plugin works with CSV files.  

Since complex external id field is a special entity dedicated to the SFDMU,  such fields don't come "normally" from the REST and so the Plugin has to construct these missing fields virtually and it does this immediatelly after receiving raw records from the REST then it appends these fields to the rest of the fields received from the org in a "normal" way.

The main point here is, that complex external id fields are always treated exactly as all other "normal" fields **as if they were received from the org**. 

Since CSV file always plays as a **final source record set** received from the REST, so it should contain all necessary fields **including complex external ids.** 

To make your migration work, just add complex external id column in your source CSV manually like other "normal" columns. In your example you shoud add the column: L_TimeEntryCode__r.$$L_SalesOrganisation__c$L_Type__c$L_Value__c
And the column data should be populated in the special format like:
"All;Premium Number;AB"
