### ISSUE TITLE
Load Account Data with a lookup to another Account record

### ISSUE THREAD

**Issue by doudou23** [forcedotcom/SFDX-Data-Move-Utility#489]
Hi,

I am struggling to load a CSV files on Account object while this account record refers to another account records.
Let say my primary account records point to a field called AssociatedAccount__c. This account record has an externalId simply called ExternalID__c.

In my export I have tried to add AssociatedAccount__r.externalId  and add the same and the corresponding value in my csv but after the load the link is never made. The tool doesn't complain about anything.

Does someone would have an example of export.json and account.csv that i could refer? 

Many thanks,
Grégory

**Comment by hknokh** [comment]
1. If your source Account.csv is already containing record ids, add AssociatedAccount__c column to the Account.csv and populate it with the parent record id value.

2. If you don't have record ids, use excludeIdsFromCSVFiles = true, then add AssociatedAccount__r. ExternalID__c column and populate it with the parent external id values.

in both cases you should set externalId = ExternalID__c and include AssociatedAccount__c into the Account query.

**Comment by doudou23** [comment]
Thanks for your fast answer , still struggling here, is there any working example published with lookup using external id?

I am trying to do that between 2 standard objects , like that you can perhaps tried and or comment whats wrong in my files. 
Below is what I defined to insert a new AccountBrand record, 2 queries in my export.json and one file with the data to insert, is there something i do wrong? 

Many thanks



{
    "apiVersion": "55.0",
    "objectSets": [
        {
            "objects": [                            
                {
                    "query": "SELECT Id, externalid__c FROM Account",
                    "externalId": "externalid__c",                    
                    "operation": "Readonly"
                },
                {
                    "query": "SELECT account, name,  Account__r.externalid__c FROM AccountBrand",
                    "externalId": "name",
                    "operation": "Insert",
                    "excludeIdsFromCSVFiles": "true"
                }

            ] 
                       
        }
    ]
}


Accountbrand.csv :

name,Account__r.externalid__c
my_little_accBrand,AccExternalID123

**Comment by hknokh** [comment]
Hello.

Generally I'm **NOT providing** help about the configuration issues, **only for breaking bugs**.

In your case you have amount of issues with the configuraiton + csv file:

- External id field declaration are case sensitive
- Proper case spelling in the fiels in the query string is highly recommended.
- All column titles in the CSV file are case sesitive.
- The names of the CSV files are case sensitive (not Accountbrand.csv but AccountBrand.csv) and should be exactly as the API name of the object
- You must provide 2 files: Account.csv and AccountBrand.csv, populated with the data even Account object is readonly in your configuration.
- You have to provide only lookup field to the Account in the AccountBrand (Account__c)
- You shoud provide corresponding columns for ALL fields in the query string in your csv file.
- Because your Account object is defined as Readonly, **you should aleady have an Account record** with ExternalId__c = AccExternalID123 in your Target org otherwize the AccountBrand will not be populated.
- excludeIdsFromCSVFiles is a global parameter across all object sets
- Since this is insert you can omit external id for the AccountBrand
- Why do you use objectSets ? Do you have multiple configurations ? I'm not sure that CSV sources are working with the objectSets, need to check this point.

**Config:**
{
  "apiVersion": "55.0",
  "objectSets": [
    {
      "objects": [
        {
          "query": "SELECT Id FROM Account",
          "externalId": "ExternalId__c",
          "operation": "Readonly"
        },
        {
          "query": "SELECT Name, Account__c FROM AccountBrand",
          "operation": "Insert"
        }
      ]
    }
  ],
  "excludeIdsFromCSVFiles": "true"
}

**Files:**
AccountBrand.csv :
Name,Account__r.ExternalId__c
my_little_accBrand,AccExternalID123

Account.csv:
ExternalId__c
AccExternalID123

**Comment by doudou23** [comment]
Many thanks for your answer, so i think i got my problem :) y
My understanding was that the tool was able to load data based on external ids in the way dataloader can do it. But I understand from your example that the external id must be provided as pre-requisite in the related object csv file. Which would become a tedious task with high volume load.

for the point : Why do you use objectSets ? Do you have multiple configurations ? I'm not sure that CSV sources are working with the objectSets, need to check this point.
->Only because i found this somewhere, actually I personally found a lack of resource or I was not able to find it :)

Once again thank you for your time and clarifying this topic :)

**Comment by hknokh** [comment]
Hello. 
You don't have to provide the externalid. it's not pre-requisite as you said.
Still there is miss-understanding there ...
Your asked regarding the external id that is why I tried to answer you in this way.
But alternatively you still can provide directly only columns for each object.
The SFDMU supports the same format as DL:
{
"objects": [
{
"query": "SELECT Id FROM Account",
"operation": "Readonly"
},
{
"query": "SELECT Name, Account__c FROM AccountBrand",
"operation": "Insert"
}
]
}

**Files:**
AccountBrand.csv :
Name,Account__c
my_little_accBrand,01XXXXXXXXXXX01

**Account.csv:**
Id
01XXXXXXXXXXX01

**Comment by hknokh** [comment]
And even this should work:
 
{
"objects": [
{
"query": "SELECT Name, Account__c FROM AccountBrand",
"operation": "Insert"
}
]
}

Files:
AccountBrand.csv :
Name,Account__c
my_little_accBrand,01XXXXXXXXXXX01

In this case the 01XXXXXXXXXXX01 is an explicit **target** Account id.

**Comment by hknokh** [comment]
Anyway I will check if it's really necessary to provide the Account.csv  for Account if it's in readonly mode.

**Comment by doudou23** [comment]
I think we still misunderstand each other, but in my dataloader load I have only one file, it would look like something

AccountBrand.csv :
Name,Account__c.External_Id__c
my_little_accBrand, external123

and in DL i can refer that the lookup need to be the External_Id__C field that's all 


Anyway I will check if it's really necessary to provide the Account.csv for Account if it's in readonly mode. -> Would be great because I tested several ways but it never relates to the related object (so far i hope :)) 

Thank you so much for your answers

**Comment by hknokh** [comment]
You are welcome.
I understand you requirement.
Thanks for the directioning me
Will review this ASAP

**Comment by hknokh** [comment]
Which dataloader are you use ?

**Comment by doudou23** [comment]
the Salesforce Dataloader, I can't paste a screenshot so i put a internet reference https://www.entrepreneurshiplife.com/wp-content/uploads/2016/10/data_loader.png

**Comment by hknokh** [comment]
Ok. Now I think I understand you.... )

Let say your AccountBrand.csv provides the value:
Account__c.External_Id__c = external123

In the target side you have the parent Account record with the values as this: 
Id = ACCIDXXXXXXXXXXX
External_Id__c = external123

You expect that the DL will then create a new AccountBrand record as:
Id = ACCBRANDIDXXXXXXXX
Account__c = ACCIDXXXXXXXXXXX
Name = my_little_accBrand

Yes, of course, the standard DL can do this... But with the one **huge** limitation: 
only when ExternalId__c **is defined as an external id filed in the field metadata.**

So, the main advantage of the SFDMU that it **does not require external id field definition** and can work with any type of external id key, even formula, compound virtual external ids etc.

As I said, I need to check this functionality how it works in the SFDMU.

**Comment by doudou23** [comment]
yeah indeed we dont make use so far of the power of SFDMU but we would like to move our load to it as it seems the future but we first need to have our basic functionalities working :d 

thank you for your time , really appreciated

**Comment by hknokh** [comment]
Hey @doudou23 
Has been fixed.
Tested with the following data:
**export.json:**
{
"apiVersion": "55.0",
"objectSets": [
{
"objects": [
{
"query": "SELECT Id FROM Account",
"externalId": "ExternalID__c",
"operation": "Readonly"
},
{
"query": "SELECT Name, AccountId FROM AccountBrand",
"operation": "Insert"
}
]
}
],
"excludeIdsFromCSVFiles": "true"
}

**AccountBrand.csv:**
Name,Account.ExternalID__c
my_little_accBrand,AccExternalID123

P/S: You should still provide Account object in the export.json because you need to tell SFDMU which external Id is there for the Account (for me it's ExternalID__c).
The advantage of SFDMU vs SF Data Loader is that your external Id can be aby Account field not only a defined as the external id using the object metadata.

**Comment by doudou23** [comment]
many thanks I will try this :)

**Comment by doudou23** [comment]
I finally got the chance to test it and I can confirm it works like a charm. 

For the community I would suggest to add this kind of example in the public documentation.

Once again, thank you very much
