### ISSUE TITLE
[HELP] - sfdmu:run is not a sfdx command

### ISSUE THREAD

**Issue by kevmaldonado95** [forcedotcom/SFDX-Data-Move-Utility#492]
When I install using:
sfdx plugins:install sfdmu
It works perfectly, I can move data.

But when I do it cloning the repository and linking it to sfdx using:
sfdx plugins:link 
In the folder of the cloned repository is not working
It says it is linked "sfdmu 4.15.1 (link) path of the cloned repo"
But when I try to run it is says:
Warning: sfdmu:run is not a sfdx command.

I don't know what is happening. I need to do it with the repo cloned because of some changes I made to the repo.

**Comment by hknokh** [comment]
Sounds like a failed installation after cloning the repo. 
It was not able to install all necessary dependencies.
You should complete the command "npm install" cleanly without any errors.
Unfortunatelly I can't suggest you something else since it's not reproducable on my side. I am always able to perform the installation and it's working as exected and I'm using the latest node.js / SFDX CLI

**Comment by kevmaldonado95** [comment]
I tried again but it is not a clean installation
![image](https://user-images.githubusercontent.com/80492293/185645181-ec8f1082-c401-4efb-ac09-75c34943fcb3.png)
Any recommendation?

**Comment by hknokh** [comment]
Typically I'm using sudo to install the plugin in MACOS
