### ISSUE TITLE
 Execution of the command was ABORTED due to unexpected error: Command failed

### ISSUE THREAD

**Issue by madhusudanreddyyalla** [forcedotcom/SFDX-Data-Move-Utility#513]
**Describe the bug**
after run the sfdx sfdmu:run --sourceusername  <username> --targetusername <username> command getting below error

C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.
Command in progress ...... done
[ERROR] Execution of the command was ABORTED due to unexpected error

[2022-10-12__18_16_45.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9765925/2022-10-12__18_16_45.log)
[Export.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9765932/Export.zip)

**Comment by hknokh** [comment]
Hello @madhusudanreddyyalla 
This issue is not related to the plugin functionality but an environment issue which I can't assist you to resolve.
Looks like for some unknown reasons the plugin can't access nodejs engine at the runtime.
The plugin has tried to call internally the sfdx force:org:display command using the CMD/Terminal, but failed to do that.
