### ISSUE TITLE
[QUESTION]-Error resolving translated standard object - Order on OrderItem.OrderId

### ISSUE THREAD

**Issue by tiagonnascimento** [forcedotcom/SFDX-Data-Move-Utility#524]
**Describe the bug**
On my customers org, Order is translated as Operation (using Setup -> Rename Tabs and Labels). Order Product (OrderItem) is also translated as Operation Product. 

I have an export involving Account, Product2, Pricebook2, PricebookEntry, Order and OrderItem. I'm first exporting it to CSVs and then importing on the target Org. The export process looks fine. During the import process, OrderId is resolved properly (as demonstrated by the file target/OrderItem_insert_target.csv). But the process to import OrderItem fails with the error: "Missing value for required field(s): Operation"

**To Reproduce**
Translate Order and OrderItem tab/label. 
Export data from source org to CSV.
Try to import data to the target org.

**Expected behavior**
OrderItem importes successfully.

**Comment by tiagonnascimento** [comment]
[sfdmu-files-issue-524.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10024165/sfdmu-files-issue-524.zip)
Zip file containing:
 - export.json
 - logs (for both export and import operations)
 - target/OrderItem_insert_target.csv

**Comment by hknokh** [comment]
Hello @tiagonnascimento 

I've had a look on your issue. 

Unfortunatelly, I can't help you with this, since it's not a runtime bug which most likely I can resolve on my side. 
The issue looks as a pure configuraiton problem, which completely depend on your processed data, so it  should be investigated only on your local system. Based on my past experience, in most cases making the export.json correct should be quite enough for this kind of issues.

Something what I can point you, that in the file ..._38.log the row:
[14:11:41.225][WARN] [Batch# 750HZ0000002ihhYAA:Insert] {Order} Incompleted. 219 records processed, 46 records failed.
which says that some of the Order records were not inserted, that can cause number of missing lookup references in the OrderItem.

In other hand, in the file ..._35.log all Order records were inserted correctly, the same regarding the OrderItem records and I did not see any issues reported.
I don't know what does it mean, but let you try to see what are the differences.

My hope is that it will give you right direction for the further investigation.
