### ISSUE TITLE
[QUESTION] - Can SFDMU do an all-or-none insert?

### ISSUE THREAD

**Issue by mmoyaferrer** [forcedotcom/SFDX-Data-Move-Utility#530]
When using SFDMU, it works in a partial success way, where the valid records are inserted even if other records fail.

In customer scenarios, this is not always the desired way, as there is the risk of leaving one Org in an unfinished status regarding data (some records inserted but some others not). Because of that, for those scenarios, validation of data or data rollback is a frequently asked feature. (When done with Apex, is a custom logic implemented in Batch Apex jobs through validation & transaction rollbacks)

When using SFDMU, I thought this could be done in 2 ways:
1. Previous validation of the data using `simulationMode`, in order that no records are inserted if there is any failure for any record.
2. If there isn't any validation, we could do a data rollback for the valid records which were inserted, in case that any other record failed.

As SFDMU doesn't have a data rollback functionality, and neither Salesforce, I tried with the 1º option, to achieve it by using `simulationMode` as a validation of the data, however, I found that it only detects missing parent records (both types lookup and master-detail) - 'MissingParentRecordsReport.csv' file is created. It doesn't validate records against e.g. validation rule or uniqueness of fields. I've checked both ways of enabling simulation mode (sfdx command flag and export.json parameter).

I would like to understand better what options SFDMU has in order to perform a pre-validation (option 1), or in case that is not possible if there should be a data rollback feature built-in (option 2).

**Comment by hknokh** [comment]
Hello

Since there is no any resonable way to rollback whole migration job containing multiple sObjects when something failing neither built-in option nor programmatically, the only way I was able to implement is the partial "simulation mode", which checks data retriving + missing relationhips between records. Since it's impossible to touch target records (no way to restore them if something went wrong), so there is no option to validate critical stuff at the target side like validation rules or triggers, which potentialy can fail a migration.

So, indeed the SFDMU has no built-in option to pre-validate a job **globally** against target org before actual update.

However, consider using the option **AllOrNone=true** **per sObject**  which records you want to rollback in case of failure. 
Note, if you want to activate this rollback feature, you have to update object records **only using REST API** (not the Bulk Api,  because the SF Bulk Api does not support rollback of batches). 
Set also **alwaysUseRestApiToUpdateRecords=true**, which forces using REST API regardless possible large number of records being updated. The disadvantage of this method is that the REST API spend more available quotas than the Bulk Api and so sometimes you can run into the limitation issues. In case of a small data set I think it whould be perfect for your use case.
