### ISSUE TITLE
[FEATURE-REQUEST] - Option to set a default owner when the owner does not exist in the destination org

### ISSUE THREAD

**Issue by SKN536** [forcedotcom/SFDX-Data-Move-Utility#535]
Currently the tool clears the owner Id or any master detail lookup value when the owner/lookup record does not exist in the destination org, causing the migration to fail. Is there a way to default the owner or default mapping incase(conditionally) the owner does not exist in the destination?

**Comment by hknokh** [comment]
Hello @SKN536 

First, please update the Plugin since I made some mandatory improvements which necessary for the SFDMU to work properly in your use case.

Regarding the default owner. You have 2 options here depending on your data.

First option is useful, if your only know the Name of the default Owner, but don't know the OwnerId. 
The SFDMU can locate and set the target OwnerId by provided Name. For that you can use the RecordsTransform Add-On.
Here is the configuration, working for me. Please, modify it as needed.
Let's say the Name of the default owner is **"Test Target User"**:

```json
{
	"objects": [
		{
			"operation": "Upsert",
			"externalId": "Name",
			"deleteOldData": true,
			"query": "SELECT Id, Name, Phone, OwnerId, RecordTypeId from Account WHERE Name IN ('ACC_10000', 'ACC_10001')",
			"beforeUpdateAddons" : [
				{                        
					"module" : "core:RecordsTransform",
					"args": {
						"fields": [
							{
								"alias": "ownerId",
								"sourceObject": "Account",
								"sourceField": "OwnerId"
							},
							{
								"alias": "defaultOwnerId",
								"sourceObject": "User",
								"sourceField": "Id",
								"isConstant": true,
								"lookupSource": "target",
								"lookupExpression": "target.Name == 'Test Target User'"
							}
						],
						"transformations": [
							{
								"targetObject": "Account",
								"targetField": "OwnerId",
								"formula": "formula.ownerId || formula.defaultOwnerId"
							}
						]
					}
				}
			]
		}
	],
	"promptOnMissingParentObjects": false
}
```

Note, that the SFDMU may warn about missing ownerid values, but it does not matter, because the Add-On will populate the missing lookup values and the update should pass well.

The second option is to use the simple ValuesMapping (if you know the exactly OwnerId value):

**export.json:**
```json
{
	"objects": [
		{
			"operation": "Upsert",
			"externalId": "Name",
			"deleteOldData": true,
			"query": "SELECT Id, Name, Phone, OwnerId, RecordTypeId from Account WHERE Name IN ('ACC_10000', 'ACC_10001')",
			"useValuesMapping": true
		}
	],
	"promptOnMissingParentObjects": false
}
```

**ValueMapping.csv**
ObjectName,FieldName,RawValue,Value
Account,OwnerId,/^$/,0058d0000054PvGAAU

The references: 
https://help.sfdmu.com/full-documentation/add-on-api/records-transform-core-add-on-module
https://help.sfdmu.com/full-documentation/advanced-features/values-mapping
