### ISSUE TITLE
[FEATURE REQUEST]-Migrate Chatterfeed with attachments

### ISSUE THREAD

**Issue by SKN536** [forcedotcom/SFDX-Data-Move-Utility#536]
**Is your feature request related to a problem? Please describe.**
Users add attachments to the chatter feed (Type: ContentPost), the tool does not migrate the attachments and associate them with the records chatter post.

**Describe the solution you'd like**
Migrate the Feed Attachments along with the Feed Item or Feed Comment.

**Comment by hknokh** [comment]
Hello @SKN536 
If I correctly understand you, you mean to transfer the ContentVersion of the FeedAttachment object, which could be retrieved by following way:
1. SELECT Id FROM FeedItem Where ParentId = 'PARENT_ACCOUNT_ID' AND Type = 'ContentPost'
2. SELECT Id, RecordId FROM FeedAttachment  WHERE FeedEntityId = 'FEED_ITEM_ID' AND Type = 'Content'
3. SELECT Id, ContentBodyId, VersionData   FROM ContentVersion WHERE id = 'FEED_ATTACHMENT_RECORD_ID'
Indeed basically it could be done using the ExportFile Add-On:
https://help.sfdmu.com/full-documentation/add-on-api/export-file-core-add-on-module
However, I must apply some update to this Add-On in order to allow handling of this kind of Files OOTB.
Putting this on my Roadmap for one of the further releases.
Thanks for the suggestion!

**Comment by SKN536** [comment]
Hello @hknokh, Thank you for adding this feature to your list. I want to make sure the upgrade works on Chatter feed Item and feed Messages Files as the newer chatter attachments are stored as Files

**Comment by hknokh** [comment]
It's should work with ContentDocument/ContentVersion objects (SF Files) attached to the FeedItem object.
FeedItem is a child of any parent record i.e. Account and represents a chatter post

**Comment by hknokh** [comment]
@SKN536 
The new option of migration chatter attachments with chatter feed items has been included in the ExportFiles Add-On.
Below is the minimal sample configuration to import (Insert) account feed items with file attachments.
The SFDMU will automatically detect and maintain relationship between objects and attachments.
```json
{
	"objects": [
		{
			"operation": "Readonly",
			"query": "SELECT Id FROM Account WHERE Name = 'ACC_10000'",
			"externalId": "Name"			
		},
		{
			"operation": "Insert",
			"query": "SELECT Id, Body, ParentId$Account FROM FeedItem WHERE Type = 'ContentPost'",
			"afterAddons" : [
				{
					"module": "core:ExportFiles"
				}
			]
		}
	]
}
```
Please test it. Thanks.

**Comment by SKN536** [comment]
Hi @hknokh when I updated the SFDMU(using instructions in here), I am not able to reinstall the plugin and get the following error:

(node:19904) [ERR_REQUIRE_ESM] Error Plugin: sfdmu [ERR_REQUIRE_ESM]: require() of ES Module D:\Users\workspace\Desktop\SFDXCLI\SFDX-Data-Move-Utility\node_modules\globby\index.js from C:\Users\workspace\AppData\Local\sfdx\client\7.181.1-05b8719\node_modules\@oclif\core\lib\config\plugin.js not supported.
Instead change the require of index.js in C:\Users\workspace\AppData\Local\sfdx\client\7.181.1-05b8719\node_modules\@oclif\core\lib\config\plugin.js to a dynamic import() which is available in all CommonJS modules.
module: @oclif/core@1.21.0
task: not loading commands, globby not found
plugin: sfdmu
root: D:\Users\workspace\Desktop\SFDXCLI\SFDX-Data-Move-Utility
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
error An unexpected error occurred: "Invalid value type 507:0 in D:\\Users\\workspace\\Desktop\\SFDXCLI\\SFDX-Data-Move-Utility\\yarn.lock".
sfdx-cli: linking plugin sfdmu... !
    Error: yarn --non-interactive --mutex=file:D:\Users\workspace\Desktop\SFDXCLI\SFDX-Data-Move-Utility\yarn.lock --preferred-cache-folder=C:\Users\workspace\AppData\Local\sfdx\yarn
    --check-files exited with code 1


Need to fix this soon as we are in midst of a production migration and reinstall blocked us completely. Can you please look into this. Thank you!!!

**Comment by hknokh** [comment]
Hello!
Unfortunately, I've tried but was not able to reproduce this issue on my side. 
Form me tehre are no issues to install it again using:
Uninstall:
```bash
sfdx plugins:uninstall sfdmu
```
Then install again
```bash
sfdx plugins:install sfdmu
```
![image](https://user-images.githubusercontent.com/15181301/210149339-9d667ef5-f34d-40d4-b955-45cf7c212f97.png)

I'm using:
![image](https://user-images.githubusercontent.com/15181301/210149381-2e7de149-5738-48e5-8d29-daa8a0203d97.png)

This issue looks like occurring due to the specific configuration of your environment and the specific data you try to migrate and that is why it should be investigated on my side.
For your reference, please have a look on [how to debug](https://help.sfdmu.com/plugin-basics/basic-usage/debugging) the plugin locally.
Thanks!

**Comment by SKN536** [comment]
Hi @hknokh  Thank you for your continuous support and improving the tool.
I was able to install it with the 'sfdx plugin:install sfdmu' command. Failed to use the setup instructions due to the missing globby or the scandir files while linking the plugin. Can you add this to installation steps so people can try this as an alternate mechanism to install incase of the failures.


Also while migrating the Files, the plugin permanently fails after migrating a few files on 'undefined/null' error when processing chunks. Anyway to ignore this and move on to the next file in case of a null failure. Here is the error I see:
[STACK TRACE] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at CsvChunks.fromArrayChunks (C:\Users\workspace\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\common_models\helpers_classes.js:167:30)
    at BulkApiV1_0Engine.createCRUDApiJobAsync (C:\Users\workspace\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\api_engines\bulkApiV1_0Engine.js:27:47)
    at BulkApiV1_0Engine.executeCRUD (C:\Users\workspace\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\api_models\ApiEngineBase.js:90:24)
    at BulkApiV1_0Engine.executeCRUDMultithreaded (C:\Users\workspace\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\api_models\ApiEngineBase.js:102:31)
    at SfdmuRunAddonRuntime.updateTargetRecordsAsync (C:\Users\workspace\AppData\Local\sfdx\node_modules\sfdmu\lib\addons\components\sfdmu-run\sfdmuRunAddonRuntime.js:159:45)
    at __writeFeedAttachmentTargetRecordsAsync (C:\Users\workspace\AppData\Local\sfdx\node_modules\sfdmu\lib\addons\modules\sfdmu-run\ExportFiles\index.js:273:48)
    at ExportFiles.onExecute (C:\Users\workspace\AppData\Local\sfdx\node_modules\sfdmu\lib\addons\modules\sfdmu-run\ExportFiles\index.js:79:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SfdmuRunAddonManager.triggerAddonModuleMethodAsync (C:\Users\workspace\AppData\Local\sfdx\node_modules\sfdmu\lib\addons\components\sfdmu-run\sfdmuRunAddonManager.js:58:30)

**Comment by hknokh** [comment]
Hello 
- Regarding the sfdx plugins:install sfdmu - its the first option already described here:
https://help.sfdmu.com/quick-start
- Regarding the issue, I can't reproduce it and it depend on your data. I can guess what is happening on your side but to fix I need to know exactly. Please attach FULL export.json + FULL log file + feeditem_insert_target.csv.   I can make my best to think about your issue remotely, but do not promise nothing. Actually, it's preferred to debug on your side.
