### ISSUE TITLE
[QUESTION] - Basic CSV file import example?

### ISSUE THREAD

**Issue by jonny-harte** [forcedotcom/SFDX-Data-Move-Utility#541]
Is there any examples of how to import a previously created csv file to a target?

**Comment by hknokh** [comment]
@jonny-harte 

You don't need any special tutorial for that. 
It's simple the same export.json is used for all types of migration (org2org, csv2org, org2csv). 
The only difference is a CLI command to run the job, while for migration between orgs you put:
```bash
$ sfdx sfdmu:run --sourceusername source@name.com --targetusername target@name.com
```
and for import csv into a target you put:
```bash
$ sfdx sfdmu:run --sourceusername csvfile --targetusername target@name.com
```
Refer here:
https://help.sfdmu.com/plugin-basics/basic-usage/running

Common info about csv import:
- You can import multiple CSVs of multiple sObjects at once.
- Create a correct export.json file with all objects and fields in your CSV files.
- CSV file can be of the standard format which the Salesforce Data Loader also accepts. 
- Run the job.

Please, let me know about any further questions.

**Comment by jonny-harte** [comment]
So I still need to include objects in my export.json even though all the columns are listed in the first row of the file?

**Comment by hknokh** [comment]
Yes, this is required file for the SFDMU. I didn't implement automatic generation of export.json from the source CSV.

But if you dont know list of fields, you can also use multiselect keywords in your queries:
https://help.sfdmu.com/full-documentation/advanced-features/field-multiselect
It can warn about missing fields in csv files (since multiselect might include a lot of field which are not in your csv), but don't worry about this. 
If you want to inport related objects, be sure you include external ids fields in export.json and columns in csvs.
I will need to check something on my end regarding setting polymorphic fields in CSV files and the format of the input CSV to be fully compatible with the standard SF Data Loader format and will let you know if any update.
