### ISSUE TITLE
Readme: broken links

### ISSUE THREAD

**Issue by TrangOul** [forcedotcom/SFDX-Data-Move-Utility#556]
The link to debugging part of the documentation ("How to debug the SFDMU") is broken (`https://help.sfdmu.com/plugin-basics/basic-usage/debugging`); 404 page is opened instead. The working one is `https://help.sfdmu.com/debugging`, but since the other links follow the `<domain>/plugin-basics/basic-usage/` template (for example `https://help.sfdmu.com/plugin-basics/basic-usage/running` instead of `https://help.sfdmu.com/running`), it should be fixed on the documentation site rather than just by changing link in the readme.

Also, the link to the "Complete guide to running the SFDMU" (`https://help.sfdmu.com/full-documentation/configuration-and-running/run-the-migration-job.md`) is not working as well. It works after removing the trailing `.md`, but the page is the same as at `https://help.sfdmu.com/plugin-basics/basic-usage/running` and `https://help.sfdmu.com/running` - possibly a redundant link to be removed?

**Comment by hknokh** [comment]
Hi
Thank you a lot for pointing me.
Fixed the readme linking.
I have linked and cataloged the documentation website anew and all seems to work correctly. 
For keeping all old links valid (since it's indexed by the google and shared across the internet), I added url rewriting. I just forgot to add some old urls to the url mapping.

**Comment by hknokh** [comment]
Closed as it's completed.
Please, let me know if you have any further questions.
Thx!

**Comment by TrangOul** [comment]
Thank you!
