### ISSUE TITLE
[QUESTION] - Can SFDMU retrieve a target Id prior to upsert in a single run?

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/SFDX-Data-Move-Utility#560]
# Question
Is there any way SFDMU can retrieve target record Ids prior to upsert from csv **in a single run**? I have been looking into the Docs to see if any feature would meet this requirement. The [RecordsTransform addon module](https://help.sfdmu.com/full-documentation/add-on-api/records-transform-core-add-on-module) looks interesting, but I'm not sure if that resolves my requirement.

# Background
I'm trying to insert Product Variations & Product Variation Parents (as part of Salesforce Commerce Cloud) from CSV into a scratch org in a CI environment. I could do the operation in two steps, first retrieving the Id either using bash + sfdx or SFDMU from target (as source) to csv and then replacing the values prior to upserting from CSV. However, this requires extra work & maintenance. Thus, I'm wondering if there exists functonality to perform this in a single run with SFDMU?

The reason why I need to retrieve an existing Id in the target is that the Product Attribute Set record (& items) [is represented as metadata](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_productattributeset.htm), and thus cannot be inserted using SFDMU as far as I understand. Thus, to resolve the product data correctly, the Product Attribute Set Id needs to be queried and replaced prior to the upsert. 

# Example
Here are the example files
export.json:
```
{
    "objects": [
        {
            "query": "SELECT Id,Name,Type,IsActive FROM Product2",
            "externalId": "Id",
            "operation": "Upsert"
        },
        {
            "query": "SELECT Id FROM ProductAttributeSet",
            "externalId": "Id",
            "operation": "Readonly"
        },
        {
            "query": "SELECT Id,ProductAttributeSetId,ProductId FROM ProductAttributeSetProduct",
            "externalId": "Id",
            "operation": "Upsert"
        },
        {
            "query": "SELECT Id,Campus__c,ProductId,VariantParentId FROM ProductAttribute",
            "externalId": "Id",
            "operation": "Upsert"
        }
    ]
}
```

ProductAttributeSet.productAttributeSet-meta.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<ProductAttributeSet xmlns="http://soap.sforce.com/2006/04/metadata">
    <developerName>ProductAttributeSet</developerName>
    <masterLabel>ProductAttributeSet</masterLabel>
    <productAttributeSetItems>
        <field>Campus__c</field>
        <sequence>0</sequence>
    </productAttributeSetItems>
</ProductAttributeSet>
```
Product2.csv (Type='Base' indicates if the Product2 is a Variation Parent):
```
Id,Name,IsActive,Type
1,Bachelor i Finance,TRUE,Base
2,Bachelor i Finance,TRUE,
```

ProductAttribute.csv (Links the Product2 to a variation parent to transform it to a variation):
```
Id,Campus__c,ProductId,VariantParentId
PA1,Oslo,2,1
```

ProductAttributeSetProduct.csv (links the variation parent to a Product Attribute Set):
```
Id,ProductAttributeSetId,ProductId
PASP1,[Replace],1
```

ProductAttributeSet.csv (record already create in the org when deploying ProductAttributeSet.productAttributeSet-meta.xml):
```
Id
[Replace]
```

Summarizing, I would need SFDMU to retrieve the ProductAttributeSet record Id and utilize it both in the ProductAttributeSetProduct.csv & ProductAttributeSet.csv, as indicated by `[Replace]`

Example files: [ProductUpsert.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10477499/ProductUpsert.zip)

**Comment by hknokh** [comment]
Hello!
Thank you for reaching out to me!
I will do my best to review your issue ASAP, but sometimes it can take a while.
You can see also the [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy).
Thx.

**Comment by hknokh2** [comment]
Hello @petter-eikeland 

I've looked onto your question, I found it very challenging.

First of all, the SFDMU can natively insert/upsert  Product Attribute Sets + Variation Products. You don't need to envolve any Core Add-On for this. It can normally handle ProductAtrributeSet records.

Below is the configuration to Upsert Product Attribute Sets and related Variation/VariationParent products. 

- See how to set **external Id** keys and **master** attribute properly: 
For VariaitonParent products -> ProductCode typically is a field having unique values.
For Variation products -> SKU is typically an unique field.
Product2 object is preffered to be set to "slave" (master=false), since we need to select only products having ProductAttributeSet assigned.

- You must use [Composite External Id Keys](https://help.sfdmu.com/full-documentation/advanced-features/composite-external-id-keys) feature because you have to guarantee uniqueness of external Id keys for each object.

- There are several mandatory fields you have to include for each object to keep this configuration running smoothly.

- The ProductAttributeSet object is in Upsert operation. If these records are missing they will be created or left untouched if exist.

```json
{
    "objects": [
        {
            "query": "SELECT Name, Type, IsActive, StockKeepingUnit, ProductClass, ProductCode FROM Product2 WHERE IsActive = true AND ProductClass IN ('Variation', 'VariationParent')",
            "externalId": "ProductCode;StockKeepingUnit",
            "operation": "Upsert",
			"master": false
        },
        {
            "query": "SELECT MasterLabel FROM ProductAttributeSet",
            "externalId": "DeveloperName",
            "operation": "Upsert"
        }
		,
        {
            "query": "SELECT Campus__c, Sequence, ProductId, VariantParentId FROM ProductAttribute",
            "externalId": "Product.StockKeepingUnit;VariantParent.ProductCode",
            "operation": "Upsert"
        },
        {
            "query": "SELECT ProductAttributeSetId, ProductId FROM ProductAttributeSetProduct",
            "externalId": "ProductAttributeSet.DeveloperName;Product.ProductCode",
            "operation": "Upsert"
        }
    ],
	"excludeIdsFromCSVFiles": true
}
```

- This configuration can be ran AS IS for org2org.

- Regarding running it for csv2org, make sure you supply CSVs **for all** objects. 
The SFDMU can't work simulatenously with mixed type of sources (org and csv).  If you set **--sourceusername csvfile,** you should provide csv file for **all objects including those having Readonly operation.** 
(I have this feature of mixed sources in my backlog, but it's not implemented yet:
https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/122 )

- Attached example of source csv files wich are quite similar to yours. 
It's not necessary to provide exact record id and lookup id columns since we have set "excludeIdsFromCSVFiles": true:

[ProductAttributeSet-Example.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10501926/ProductAttributeSet-Example.zip)

**Comment by hknokh2** [comment]
@petter-eikeland 

Just now I've applied fix for the Smart Order feature, which will improve handling of Product Variations. 
Please update the Plugin.

---

See below another configuration to **Insert** **new** Product Attribute Sets and related Variation/VariationParent products.
Sample csv files are also attached.
CSV files for insertion are very simple since unlike CSVs for Update they do not contain composite external id columns.
Record Id is an external ID key for all inserted objects.
ProductAttributeSet object is set to Readonly because you already have it in the Target.

In this example I'm removing the old records with **"deleteOldData": true** and inserting new records.

I'm using deleteQuery to delete specific products. Customize my example upon your specific use case.

```json
{
    "objects": [
        {
            "query": "SELECT Name, Type, IsActive, StockKeepingUnit, ProductClass, ProductCode FROM Product2 WHERE IsActive = true AND ProductClass IN ('Variation', 'VariationParent')",
			"deleteQuery": "SELECT Id FROM Product2 WHERE Name LIKE 'Bachelor%'",
            "operation": "Insert",
			"deleteOldData": true,
			"master": false
        },
        {
            "query": "SELECT MasterLabel FROM ProductAttributeSet",
            "externalId": "DeveloperName",
            "operation": "Readonly"
        }
		,
        {
            "query": "SELECT Campus__c, Sequence, ProductId, VariantParentId FROM ProductAttribute",
			"deleteOldData": true,
            "operation": "Insert"
        },
        {
            "query": "SELECT ProductAttributeSetId, ProductId FROM ProductAttributeSetProduct",
			"deleteOldData": true,
            "operation": "Insert"
        }
    ],
	"excludeIdsFromCSVFiles": true
}
```
 
[ProductAttributeSet-Example-Insert.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10514207/ProductAttributeSet-Example-Insert.zip)

**Comment by petter-eikeland** [comment]
Thank you so much @hknokh2 for your great support and detailed example! This resolved my issue

Have a great weekend 🕺

**Comment by hknokh2** [comment]
@petter-eikeland 
FYI. I've implemented this feature:
https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/122
Now you have an extra option to insert your all variation data using org2org and only the ProductAttributeSet records can import from csv file.
Use the script as below and put ProductAttributeSet.csv into the working directory.

```json
{
    "objects": [
        {
            "query": "SELECT Name, Type, IsActive, StockKeepingUnit, ProductClass, ProductCode FROM Product2 WHERE IsActive = true AND ProductClass IN ('Variation', 'VariationParent')",
			"deleteQuery": "SELECT Id FROM Product2 WHERE Name LIKE 'Bachelor%'",
            "operation": "Insert",
			"deleteOldData": true,
			"master": false
        },
        {
            "query": "SELECT MasterLabel FROM ProductAttributeSet",
            "externalId": "DeveloperName",
            "operation": "Readonly",
            "useSourceCSVFile": true
        },
        {
            "query": "SELECT Campus__c, Sequence, ProductId, VariantParentId FROM ProductAttribute",
			"deleteOldData": true,
            "operation": "Insert"
        },
        {
            "query": "SELECT ProductAttributeSetId, ProductId FROM ProductAttributeSetProduct",
			"deleteOldData": true,
            "operation": "Insert"
        }
    ],
	"excludeIdsFromCSVFiles": true
}
```
