### ISSUE TITLE
[QUESTION]-Self-referencing lookups handled as Insert and Update instead of 2 inserts

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/SFDX-Data-Move-Utility#593]
**Describe the bug**
Apologies if this has been asked before. I didn't find any similar issues. Also didn't find anything related on the Docs.

When inserting records with lookups to itself, it is handled as an insert and an update instead of 2 inserts (1 insert of parents, then an insert of the childs). However, when inserting records with lookup to a different object (e.g. an Account and a Contact) this lookup is handled using 2 inserts and no update. This affects how testdata is generated in our scratch orgs (insert vs. update triggers). This occurs both when inserting/upserting from CSV and from another org.

**To Reproduce**
1.  Create a Parent__c lookup field on Product2
1.  Create csv with a parent and a child record (see attached CSV)
1.  Run `sfdx sfdmu:run -s csvfile -u [Alias] -p src/test-data --noprompt`

**Expected behavior**
"Parent" products (Parent__c = null) are inserted first. Then child products with lookup to Parent populated are inserted second

**Actual behavior**
All Products are inserted. Then relationships are resolved as an update. Relationships between different objects are resolved with the expected behavior above (e.g. Account & Contact)

**export.json**
```
{
    "objects": [
        {
            "query": "SELECT Id, Parent__c, Name FROM Product2",
            "externalId": "Id",
            "operation": "Insert"
        }
    ]
}
```

**Log file**
[log file.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/11405694/log.file.txt)

**_target.csv** file.
[Product2_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/11405669/Product2_insert_target.csv)
[Product2_update_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/11405670/Product2_update_target.csv)

**NB!** I also tried the same with v. 4.26.13

**Comment by hknokh2** [comment]
Hello,

I apologize for the delay in response. I have reviewed your case and unfortunately, I cannot make any changes to the way the SFDMU handles self-reference fields. This is because, based on my understanding, there are logical inconsistencies in certain cases if the behavior is altered.

Allow me to explain in detail:

1. Insertion of self-reference fields:
   When inserting records with self-reference fields, let's consider the example of the Account object. During the initial insertion pass, you should only insert records that do not have child->parent references to other parent account records.
   The reason for this approach is that some of the inserted records may reference records within the same record set you are currently inserting. Therefore, until the first-level records are inserted, we don't know the target record IDs required to populate the lookup fields.

2. Second pass during the update phase:
   In the second pass, you will have two types of records:
   a) Records that have already been inserted and require updates to their child lookup fields, which reference parent records from the same record set already inserted in the target. We already have their record IDs available to populate the child records.
   b) Records that do not belong to the same record set but reference records that already exist in the target. These records also have their corresponding record IDs to populate their child records.

The SFDMU tool is not designed to perform insertions and updates in the same pass when the primary operation is insertion. Instead, it utilizes the update operation to populate child lookup fields that point to both types of records mentioned above.

I hope this clarifies the behavior of the SFDMU plugin in relation to self-reference fields. If you have any further questions, please let me know.

Regards.
