### ISSUE TITLE
[QUESTION] - Does the field mapping affect the ExternalId field for upserts?

### ISSUE THREAD

**Issue by jhawk-4** [forcedotcom/SFDX-Data-Move-Utility#610]
I'm looking to migrate accounts from one org to another.  I plan to store the source account Ids on an external ID field in the target org.  This field only exists in the target org and not the source org.  If I set the externalId property to be Id and then map the Id field to the external Id field in the target, would this scenario be supported?  My testing seems to indicate, no, but wanted to verify just in case I was doing something wrong.  When I executed this, it was always attempting to insert.  After the initial insert, no updates were ever attempted and I would get duplicate errors because it was attempting to reinsert the records instead of update.  Below is the export.json file example.

```
{
    "objects": [
        {
            "query": "SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, BillingLatitude, BillingLongitude FROM Account WHERE Id IN (listOfIds)",
            "operation": "Upsert",
            "externalId": "Id",
            "master": true,
            "useFieldMapping": true,
            "fieldMapping": [
                {
                    "targetObject": "Account"
                },
                {
                    "sourceField": "Id",
                    "targetField": "Source_Record_Id__c"
                }
            ]
        }
    ]
}
```

The initial insert did map the ID to the Source_Record_Id__c field correctly, it just didn't use that field as the upsert key on subsequent runs.  If Id is specified as the externalId does it just always attempt an insert instead of an upsert, or was the fieldMapping not used to replace the externalId?

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me. 
In general, the sfdmu does support mapping of ID to other field. This means that the values of the ID will be **copied** to the desired target field.
But the target mapped field isn't become externalid instead of ID in the target side. The external ID is always ID in thr both side. 
Cheers.

**Comment by hknokh2** [comment]
Hello,
OK.  Thank you for the suggestion.
I will check this.
Best regards.

**Comment by hknokh** [comment]
Hello.

I sincerely apologize for the extended delay in resolving your ticket. I understand that you have been waiting for a resolution, and I regret any inconvenience this has caused.

Due to my current time constraints and commitments, I am unable to provide timely support for this project. However, please be assured that I value your inquiry and will review this ticket again as soon as my schedule permits.

Your patience is greatly appreciated, and I will do my best to address your concerns as soon as possible.

Thank you for your understanding.

Best regards.

**Comment by hknokh** [comment]
I've temporarily closed this case for now and will revisit it in the future. 
Once there's an update or outcome, I will reopen it and notify you.
