### ISSUE TITLE
[QUESTION] Unable to Query more than 100000 records if queryAllTarget is True in Update operation

### ISSUE THREAD

**Issue by swapnilmr2** [forcedotcom/SFDX-Data-Move-Utility#632]
**Describe the bug**
I am updating person accounts from production to Sandbox. Sandbox has more than 100k records but while querying in target it only fetches 100K records. Its seems some limit is set.

**To Reproduce**
Try to perform update operation in sandbox environment where record count is more than 100k and queryAllTarget is True

**Expected behavior**
Tool should query allrecords in sandbox to update data accurately 

**export.json**
[exportFile.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12556865/exportFile.txt)

**Log file**
[Uploading 2023-09-08__12_17_39.log…]()

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment]
Hello.

Thank you for reaching out to me. I appreciate your patience and understanding.

Firstly, I regret to inform you that I am currently unable to download and review your log file. Secondly, I do not have the opportunity to reproduce your issue as I lack a suitable test environment for processing a large number of records. Please note that there is no limitation on the number of fetched queries; it is only constrained by the node.js heap size.

I believe the root cause of this unusual behavior may be related to your organization's data and settings. I recommend reviewing these aspects to identify any potential issues.

Unfortunately, due to temporary time constraints, I am unable to provide active support for this project at the moment. I apologize for any inconvenience this may cause and appreciate your patience as I am unable to suggest the best course of action at this time.

Thank you for your understanding.

Best regards.

**Comment by swapnilmr2** [comment]
@hknokh  issue is similar to this issue - https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/522

any idea how to setup highwatermark in node.js

**Comment by hknokh** [comment]
Hello,

I'm not convinced that this is related to #552. Issue #552 pertains to the jsforce limitation of 1M, which isn't a Node.js issue.
For your reference, in Node.js you'd set it up like this:
const fs = require('fs');
const readableStream = fs.createReadStream('file.txt', {
  highWaterMark: 16 * 1024 // 16KB
});
However, this configuration won't be of assistance with SFDMU.
