### ISSUE TITLE
[QUESTION] - How to insert Authorization Form & Authorization Form Text (Master-detail)

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/SFDX-Data-Move-Utility#638]
I'm struggling with insertion of Authorization Form & Authorization Form Text using SFDMU. Might be related to the fact that it's a master-detail relationship.

If I'm using **Name** as externalId on AuthorizationForm, then I get a dummy (Parent) Authorization Form record with Name=`ID0000000000000001` when inserting the Authorization Form Texts. If I use Id as externalId on Authorization Form, then the Authorization Form Texts are not inserted due to missing Parent Lookup. 

How do I insert the Authorization Form (Parent) and the 3 Authorization Form Texts (Children) using SFDMU?

I have attached the sample csvs and export.json below:
[AuthorizationForm.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12658349/AuthorizationForm.csv)
[AuthorizationFormText.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12658350/AuthorizationFormText.csv)
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/12658353/export.json.txt)

**Comment by hknokh** [comment]
Hello.

Thank you for reaching out to me. Based on the information you've provided, it appears that this is not a bug related to the Plugin.

For issues of this nature, please consult the SFDMU Help Center documentation at https://help.sfdmu.com/. Additionally, you can review our support policy at https://help.sfdmu.com/full-documentation/additional-information/support_policy to understand the types of issues that fall within the scope of my assistance.

Thank you for your understanding and cooperation.

Regards.

**Comment by petter-eikeland** [comment]
Hi, thank you for your response. I marked it as a question, because I wondered how can I ensure that Master-Detail objects are inserted correctly? It seems like I cannot do the same as for regular Parent Child Lookup Relationships? 

Do I have to insert the Master in one execution and then the Details in another? Or is SFDMU able to insert both Master and Detail and resolve the relationships correctly in the same `sf sfdmu:run` ?

**Comment by hknokh2** [comment]
Hello,

The SFDMU is designed to handle both MD (Master-Detail) and regular lookup relationships correctly.

Your export.json seems to have some inaccuracies. As explained in the following link:
https://help.sfdmu.com/faq/configuration/can-i-omit-external-id-definition-for-the-object,
you can use the record ID as an external ID only for Insert operations. Since your operation is an Upsert, it will not function correctly for the AuthorizationFormText object.

For your specific scenario, if you're attempting to insert records using the CSV files provided, it won't succeed because the files are not formatted correctly. A potential solution would be to set the flag "excludeIdsFromCSVFiles" to true. You can learn more about this parameter here:
https://help.sfdmu.com/full-configuration.
For further understanding, you might find this example helpful, even though it's slightly different:
https://help.sfdmu.com/examples/configuration/csv-import-export#example-1-import-accountbrandcsv-without-providing-accountcsv.

The correctly formatted CSV files for your case should resemble the example below:

**AuthorizationForm.csv:**
Name,RevisionNumber
"Consent v1.0",1

**AuthorizationFormText.csv**
Name,AuthorizationForm.Name
Email Newsletter,"Consent v1.0"
"Social media, such as Facebook or Instagram","Consent v1.0"
SMS,"Consent v1.0"

Hope it will help.

Regards.

**Comment by petter-eikeland** [comment]
Thank you so much @hknokh! This made it a lot clearer to me :)

**Comment by gorankarabeg** [comment]
Hi. 

I have the same issue as Petter here. I tried to follow guide described here in this article on SFDMU Help Center:
https://help.sfdmu.com/faq/sfdmu-data-insertion-and-limitations/how-to-handle-master-detail-relationships-with-sfdmu 
but I still don't get any AuthorizationFormText records.
I've used exactly the same files as described in the article ( export.json, AuthorizationForm.csv, AuthorizationFormText.csv ).

Is there any place to read SFDMU logs?
I don't see any error during scratch org creation.

thanks
-Goran
