### ISSUE TITLE
[QUESTION] - How to migrate Rich Text Area fields with images

### ISSUE THREAD

**Issue by 6andrey** [forcedotcom/SFDX-Data-Move-Utility#641]
Hello!
I wonder if the any ways to use SDFMU to migrate RTA field with embedded images?
Will appreciate any idea!

So far, I understand that:
- Image on RTA field cannot be replaced with an image link (like, e.g., it is done on InApp Guidance)
- Image can be downloaded via [REST API](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_rich_text_image_retrieve.htm)
  - image ref on the RTA field is coded as `<img alt=\"johnSmithPhoto\" src=\"https://MyDomainName.documentforce.com/servlet/rtaImage?eid=a005e000007Dksm&amp;feoid=00N5e00000djU6Y&amp;refid=0EM5e000000B9LQ\"></img>`

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me.

RTA is transferred as is, like other types of fields, without any transformations. If you have an image as HTML, it will be populated as it was in the source record. For your scenario, you will need permissions to access images via servlet. I would recommend converting and embedding the image in the source into base64 image format instead of linking to the source directly. This conversion should be performed before uploading to the target. Please note that SFDMU does not have a built-in feature to download, populate images, or other binaries and embed them.

If a more complex transformation is needed before populating the target, consider customizing the transformation using the following resource:
[SFDMU Records Filter Core Add-On Module](https://help.sfdmu.com/full-documentation/add-on-api/records-filter-core-add-on-module)

Cheers.
