### ISSUE TITLE
[BUG] - When using skipExistingRecords lookups to existing records does not work

### ISSUE THREAD

**Issue by kalius** [forcedotcom/SFDX-Data-Move-Utility#655]
Hi,

skipExistingRecords flag is not working correctly if record to be inserted does have lookup to a record which already exists in org.

**To Reproduce**
1. Create manually an Account record with name: ParentAccount
2. Use this export.json 
 ```
{
    "createTargetCSVFiles": true,
    "excludeIdsFromCSVFiles": true,
    "useSeparatedCSVFiles": true,
    "objects": [
        {
            "query": "select Name,ParentId from Account where Name IN ('ParentAccount','ChildAccount')",
            "operation": "Upsert",
            "externalId": "Name",
			"skipExistingRecords":true
		}
    ]
}
````
3. and CSV
```
Name,Parent.Name
ChildAccount,ParentAccount
ParentAccount,
````
**Expected behavior**
ChildAccount should have ParentId value, but it hasn't. 

If you run command again and change skipExistingRecords to false, ParentId will get correctly populated.

**Comment by kalius** [comment]
This issue should still be reviewed...

**Comment by hknokh2** [comment]
Apologies for the confusion earlier. To clarify, you are indeed right that the skipExistingRecords feature is designed to work with 'Upsert' rather than 'Insert' operations.

Regarding the handling of self-referential lookups, my previous explanation remains accurate—they should be populated in a subsequent 'Update' cycle following the insertion of the parent records.

However, I need to examine why, in your specific scenario, the self-referential lookups are not being populated during this update cycle. Unfortunately, this investigation may require some time. I sincerely regret any inconvenience this may cause and thank you for your understanding.

**Comment by hknokh** [comment]
I  put this issue for further review

**Comment by kalius** [comment]
> Apologies for the confusion earlier. To clarify, you are indeed right that the skipExistingRecords feature is designed to work with 'Upsert' rather than 'Insert' operations.
> 
> Regarding the handling of self-referential lookups, my previous explanation remains accurate—they should be populated in a subsequent 'Update' cycle following the insertion of the parent records.
> 
> However, I need to examine why, in your specific scenario, the self-referential lookups are not being populated during this update cycle. Unfortunately, this investigation may require some time. I sincerely regret any inconvenience this may cause and thank you for your understanding.

I've performed another test and it seems that this error occurs only on self-referential lookups (e.g. account->accounts), on others (e.g account->contacts) works correctly.
