### ISSUE TITLE
Known limitations for Large Data volume Migration

### ISSUE THREAD

**Issue by chanchalpawan2** [forcedotcom/SFDX-Data-Move-Utility#662]
Need help with these two questions for SFDMU

Question #1.Are there any known limitation of SFDMU  around large data volume migration
Like if its more 1 million then SFDMU might crash/hang or any special consideration we need to keep in mind.

Question #2.Similary are there any known limitation around using SFDMY for large set of file migration. 
How to leverage SFDMU for 700 K + files migration.

**Comment by hknokh2** [comment]
Hello,

Thanks for reaching out! Here's a quick rundown:

1. Theoretically, there's no max data size limit. However, due to Node.js memory constraints, it's practical to work with 700-1000K of data across all objects in the config. You might find these links helpful for related issues:
   - [ECONNRESET Error During Source Data Retrieval](https://help.sfdmu.com/troubleshooting/plugin-wont-run/read-econnreset-error-during-retrieving-the-source-data)
   - [Resolving JavaScript Heap Out of Memory Error](https://help.sfdmu.com/troubleshooting/plugin-wont-run/i-have-an-javascript-heap-out-of-memory-error-how-to-resolve)

2. About record transfers, it's as mentioned above. For attached files, consider using local caching to migrate files. More info here: [Full Configuration](https://help.sfdmu.com/full-configuration) - check out the binaryDataCache option.

For an example of how to transfer files, this link might be useful:
[File Migration Configuration Example](https://help.sfdmu.com/examples/configuration/file-migration)

Cheers!

**Comment by 3sneha123** [comment]
Thank you for your response.
Does it mean, if data volume is more than 2-3 million, this might not be an ideal tool for Data migration?
I would like the scenario where this SFDMU might not be an ideal solution.

**Comment by hknokh2** [comment]
I can't specify an exact scenario where SFDMU isn't the ideal solution, but it's true that it can't process unlimited data volumes. However, if your query only includes a few fields, it might handle a query of 2-3 million records.

The reason is that SFDMU is primarily designed for different purposes rather than processing extremely large data volumes:
a) to facilitate direct org-to-org migrations, b) to manage relationships between objects without complications...

For very large data volumes, consider using Salesforce's standard data loader. While it lacks some of the sophisticated features that SFDMU offers, it may handle 2-3 million records of a single table more effectively.

So, as mentioned, if your data is too large, it's advisable to experiment and see if it can be managed effectively.

**Comment by nazim-aliyev** [comment]
Just faced one:

`[ERROR] Error during execution of the command: Error occured while reading from the CSV file C:\Users\XXXXX\Downloads\data\User.csv: File size (10654048182) is greater than 2 GiB.. `

We have an object with ~5mln rows but many columns filled with data.
