### ISSUE TITLE
[FEATURE REQUEST]-Editable fields should check target object rather than query object

### ISSUE THREAD

**Issue by samarmstrong111** [forcedotcom/SFDX-Data-Move-Utility#672]
**Is your feature request related to a problem? Please describe.**
Migrating system-only records such as CaseMilestone does not work due to the restriction on requiring editable fields in the query. 
CaseMilestone is not available for Create, Update, or Delete, but it is readable. During migration we want to port this to a legacy object so that we're maintaining audit history, but no insert occurs as the fields are not editable according to this post in the help https://help.sfdmu.com/troubleshooting/common-issues/why-no-records-inserted

**Describe the solution you'd like**
When performing an insert/upsert operation, the checks should be done on the fields on the target object rather than the query object. 
Alternatively, there should be an option to allow this operation to be attempted anyway and bypass this restriction.

**Comment by hknokh2** [comment]
Hello,

Thanks for your suggestion. 
Currently, field accessibility checks are performed on both the source and target organizations. 
A straightforward solution could be to introduce two new properties for the object: skipSourceFieldsValidation and skipTargetFieldsValidation. These would allow users to optionally bypass field validation on either side.

I've added this to my development backlog.

Cheers.

**Comment by samarmstrong111** [comment]
This may be connected, or I can open a separate issue. 
We copied cases over, and the external id on the target org is a new external id text field where we copied the old CaseNumber field into. When trying to update these records later it will always tell me that there are no differences between the two records, even though the fields on the target are completely blank, and the old system has these fields populated. 
I believe this is likely down to this https://help.sfdmu.com/faq/configuration/can-i-use-autonumber-fields-as-external-id despite that the external id of the target is not autonumber, but it is mapped from an autonumber on the source. 

In general it would be nice to just have an "I know what I'm doing" option that bypasses any form of validation like this, because generally the source org's setup doesn't matter compared to the target.

**Comment by hknokh2** [comment]
Hello,

Apologies for the very delayed response. Regarding the external ID setting, it won't function as expected. The external ID key for an update should be a previously filled external ID field, present in both the source and target. The comparison of external IDs is conducted before any updates are made. This is crucial because, in order to update existing records, the plugin needs to select only those target records that match the source records. This selection is possible only through the use of previously filled external IDs.

Regarding the feature request of above, unfortunately, due to time constraints, I won't be able to address it immediately but rest assured, I believe it will be done quite soon. Thank you for your patience and understanding.

Regards.

**Comment by hknokh2** [comment]
Hello,

Following your request, I've added a new property to the ScriptObject: `skipRecordsComparison`. This property enables you to bypass record comparison, ensuring updates occur in every case, regardless of whether the data is identical.

Please ensure you update the Plugin accordingly.

Best regards.
