### ISSUE TITLE
[QUESTION] Execution failed due to errors or warnings. Ensure SFDX CLI is installed, the plugin is in place, and review script and error logs for issues.

### ISSUE THREAD

**Issue by SFDMUTOOL** [forcedotcom/SFDX-Data-Move-Utility#693]
@hknokh 
Background of the issue : When I am running new version 4.2.0 from GUI I am getting the below  warning 
Issue: Execution failed due to errors or warnings. Ensure SFDX CLI is installed, the plugin is in place, and review script and error logs for issues.
Steps What  I did to install the new version in my machine based on your GUI Document.
Step 1:  I have install  https://visualstudio.microsoft.com/vs/community/
Step 2: Install the CLI and my version is @salesforce/cli/2.30.8 win32-x64 node-v20.11.1
Step 3 :  I have install https://www.python.org/downloads/
Step 4: Install the npm install --global node-gyp
Step 5 : Clone this repository: git clone https://github.com/forcedotcom/SFDX-Data-Move-Utility-Desktop-App.git
Step 6 : # Go into the project directory: cd SFDX-Data-Move-Utility-Desktop-App
Step 7 : npm install
Step 8 : npm run build
step 9: npm start

Connection also established from Source to destination org but still I am getting the error 

Still I  am getting this error: Execution failed due to errors or warnings. Ensure SFDX CLI is installed, the plugin is in place, and review script and error logs for issues. Where I have missed could you please tell me. I am struck on this. 
This is the command while we I am running . I have checkd
sf sfdmu run --sourceusername UatGalaxyOrg --targetusername Dev2GalaxyOrg --path "C:\Users\gnavula\Documents\SFDMU-GUI-APP-DATA\workspaces\SFDMU-TOOL\Default--1-gourav" --filelog 1 --loglevel TRACE

Where I have missed please help me for the same.

Regards
Gourav Narula

**Comment by hknokh** [comment]
Hello,

Thank you for reaching out.

The issue you're experiencing isn't related to the GUI installation. If the GUI app runs properly, that aspect is fine. The problem lies in executing export.json on macOS. Specifically, if you're on macOS and using version 4.2.0 of the GUI, you'll encounter an issue where the job fails to start from the Run step button.

For a solution, please refer to this fix: [https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/671](https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/671). Update your GUI to the latest version and then attempt to run the job again.

Cheers

**Comment by SFDMUTOOL** [comment]
Hey @hknokh ,

Thanks for the update but  I am using windows not macos.. Can we connect for the same. 
Regards
Gourav Narula

**Comment by SFDMUTOOL** [comment]
Hey @hknokh , 

I have direct run the command in the console. Please find the attachment for your reference. Still getting the error.
![error](https://github.com/forcedotcom/SFDX-Data-Move-Utility/assets/161153675/f5c0b0a9-06d2-44dc-a103-d334b0fd3159)

**Comment by hknokh** [comment]
Hello.

I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.

Regards.
