### ISSUE TITLE
[QUESTION] - Use externalId to match parent-child records instead of standard ID.

### ISSUE THREAD

**Issue by kratoon** [forcedotcom/SFDX-Data-Move-Utility#698]
Hi, thanks for super cool library.

**Description**
I struggle with one issue while populating parent fields, not sure if it's a bug or I'm missing something in my config.
In my use case, I want to avoid using standard IDs completely, there are several reasons, e.g.:
1. We want to commit those data in git and ID would change frequently which would cause messy PRs and commits.
2. We want to export only child objects from a sandbox and match them with parent records already committed in git. Parents could be exported from a different sandbox, hence the matching would not work when standard ID is used.
3. When building CSV file without exporting the data.

**Assumption**
My expectation was that the "externalId" would be used to match child to parents. Seems like ID is always used instead.

**Example Config**
This config with IDs works and Product Options have the Configured SKU populated after import:
```
{
  "objects": [
    {
      "operation": "Upsert",
      "externalId": "Name",
      "query": "SELECT Id, Name FROM Product2"
    },
    {
      "operation": "Upsert",
      "externalId": "Unique_External_ID__c",
      "query": "SELECT Id, SBQQ__ConfiguredSKU__c FROM SBQQ__ProductOption__c"
    }
  ]
}
```

whereas a config like this without standard IDs does not work, records are created but the SBQQ__ConfiguredSKU__c is null on all records even though the Name attribute matches the names in the Product2 CSV.
```
{
  "objects": [
    {
      "operation": "Upsert",
      "externalId": "Name",
      "query": "SELECT Name FROM Product2"
    },
    {
      "operation": "Upsert",
      "externalId": "Unique_External_ID__c",
      "query": "SELECT SBQQ__ConfiguredSKU__r.Name FROM SBQQ__ProductOption__c"
    }
  ]
}
```

The `SBQQ__ConfiguredSKU__c` is just a lookup to the Product2 object.

**Question**
So my question is, is it expected that ID is used to match parent-child relationships? Is there a way to change this behaviour to use the "externalId" instead?

Thank you!

**Comment by kratoon** [comment]
Based on these two articles I would say it's not possible to avoid the ID field being used to match parent-child records. This is unfortunate for anyone using git in their pipeline 😢 

- https://help.sfdmu.com/faq/configuration/can-i-also-export-some-fields-from-the-referenced-parent-sobjects-using-the-child-object-query
- https://help.sfdmu.com/faq/configuration/should-i-always-include-id-field-in-my-query

**Comment by hknokh2** [comment]
Hello,
Thank you for reaching out to me and for the positive feedback about the tool.
I will take a look at your case and let you know if there are any updates.
Cheers.

**Comment by hknokh** [comment]
Hello,

It appears the articles you've shared might not directly address your question. 

From what I gather, you're looking to use a custom field as an external ID instead of the standard record Id field. This is indeed possible and represents one of the key features of SFDMU!

Additionally, you're interested in excluding Id fields and lookup id fields when generating CSV files for the child objects for your repository, with the aim of importing from those CSV files even when Id and lookup Ids are absent. 
For this purpose, I recommend utilizing your first version of export.json configuration but adding **excludeIdsFromCSVFiles=true** to the root of your export.json file.
Note that csv files should be generated under this property to set to true to ensure that all necessary columns are present (besides record ids and lookup ids).

For more detailed guidance, please visit: https://help.sfdmu.com/full-configuration.

Best regards.

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
