### ISSUE TITLE
Unable to set the Batch Size during CRUD Operations. The bulkThreshold setting not enforced

### ISSUE THREAD

**Issue by genoud** [forcedotcom/SFDX-Data-Move-Utility#7]
Setting the `bulkThreshold` setting in the `export.json` does not affect the batch size used during insert/update/delete operation.

**Comment by genoud** [comment]
Can push a fix for this.

**Comment by hknokh** [comment]
Hello!
Thank you for your mention.
But need to clarify the meanings, that the bulkThreshold  is not the same as the CONSTANTS.MAX_BATCH_SIZE
bulkThreshold  means the max number of the source records when the Plugin switches from processing the source records using regular REST API to processing them using Bulk API.
But when the records are being processed using Bulk API the batch size always remains closest to 10000 records per batch as it is standard limit of the batch in SF Bulk Api V1.
In the Plugin there is no option to control the batch size as you wish. The batch size is constant and currently it is 9500 - near the limit.
I am currently working on implementation of Bulk Api V2 instead of Legacy V1 as it is now. 
Please, follow the repo changes regarding this.
As known, in the new Bulk API V2 - the limitations defined by the Job but not by the Batch and depend on binary size of the input csv file in base64 format.
Best regards.

**Comment by genoud** [comment]
Hello,

Thanks for your answer. 
We could export the constant `CONSTANTS.MAX_BATCH_SIZE` to make it configurable from the `export.json` file. This would help play on the Batch Size while waiting the implementation of Bulk Api V2.

We need to play with that variable in other to import our data.
Thanks for the tool.

Regards,

**Comment by hknokh** [comment]
Hello!
I am putting it on the roadmap milestone.
Thank you for the suggestion.

**Comment by hknokh** [comment]
Hello!
You requested feature has been implemented.
Now you can control the max Bulk Api V1 batch size by the new global json parameter bulkApiV1BatchSize. To apply the change on your local, please uninstall the plugin and install it again.
Regards.

**Comment by genoud** [comment]
Hello @hknokh 

Thanks, Just tested and it works well.

Regards

**Comment by hknokh** [comment]
Hello @genoud !
I'm happy that it's working for you.
I just have  implemented the Bulk V2 and it is from now to be used by default for the bulk jobs. Could you please to test it for your use case and let me know how is it?
Thank you in advance.

**Comment by genoud** [comment]
Hello @hknokh ,

Just tested the v2 and it is working fine. 

Thanks

**Comment by hknokh** [comment]
Hello @genoud 
Thank you for the update!
