### ISSUE TITLE
New version is not working[BUG]-The bug title

### ISSUE THREAD

**Issue by SFDMUTOOL** [forcedotcom/SFDX-Data-Move-Utility#700]
**Describe the bug**
I am trying to transfer the account data from Source org to target org in the new version. In my case my source org is the uat org and the target org is org is the dev org.  I have written one SOQL query to get the records.  I have attached the export.json file also.

**To Reproduce**
In previous version I  am getting the options salesforce org to salesforce org but int the new tool I am not getting that option also.

this is the below command I am using 

sf sfdmu run --sourceusername UatGalaxyOrg --targetusername Dev2GalaxyOrg --path "C:\Users\gnavula\Documents\SFDMU-GUI-APP-DATA\workspaces\SFDMU-TOOL\SFDMUUtility" --filelog 1 --loglevel TRACE

**Expected behavior**

**export.json**
[export1 (2).json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14733065/export1.2.json)

**Log file**

This is my log files : 
[2024-03-23__22_58_39.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14733075/2024-03-23__22_58_39.log)

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

No data transfer to the target org. My Previous version is working as expected there  is no issue But I want to used of new version also . 
Please help me for the same.

**Comment by hknokh2** [comment]
Hello.
You should put your objects in the root "objects" array of the script, not in the second item of the objectSets array.
Regards

**Comment by SFDMUTOOL** [comment]
Hey @hknokh , 

Thanks for the update . Could you please let me know form where I can disabled this object set array features from GUI . I dont want to add the object set array . 
[export.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14757100/export.json)
This is my export,json file When I am running directly tis working expected. 
But as of now I don't want the object set array under the object so from where I can disable the feature from  UI. 
Regards
Gourav Narula

**Comment by hknokh2** [comment]
Hello
I think you need nothing to do here.
Because, when you have only one object set defined in the gui, finally the gui generates export json file containing root "objects" array and does not included objectSets array at all.
ObjectsSets array is generated for export json containing more than one set of objects.
Regards.

**Comment by SFDMUTOOL** [comment]
@hknokh ,

Thanks for the update. 

I just want to know one more thing . Old gui version is also working for me. I am used to of that version I just want to know you never decommission- the old version also or is better to use the new version . In future you will not decommission the new version also

**Comment by hknokh2** [comment]
The old version of the GUI has been archived and will no longer receive maintenance updates. In contrast, the new version will continue to be maintained. As of now, I have no plans to redesign it in the foreseeable future. Of course, transitioning to the new version is advisable due to its support for the latest SFDMU features. I aim to keep it in sync with the most recent SFDMU versions and enhancements.

**Comment by hknokh** [comment]
Hello.

I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.

Regards.
