### ISSUE TITLE
Unable to upsert records for multiple related SObjects altogether

### ISSUE THREAD

**Issue by AnjaliGoenka4** [forcedotcom/SFDX-Data-Move-Utility#711]
Hi,
When I am upserting the records for one SObject like Account only, the command is loading and working as expected but when I try to upsert records for multiple related SObjects like Account, and Contact(lookup to Account object), the terminal keeps on showing 'Command in Progress' and there is no result or error even after waiting for a long time.
How can I achieve the same?

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out to me. 
Just checked the plugin. Everything is working as expected on my side for a group of related objects. It seems there could be issues related to installation, internet connection, or configuration. The problem mostly appears to be related to interruptions in the internet connection, but it could also be due to processing a very large number of records. In any case, it is not an issue with the SFDMU itself.

Cheers.

**Comment by hknokh** [comment]
This case is now considered resolved, and I am closing it for now. 
If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
