### ISSUE TITLE
[FEATURE REQUEST] - Generate source csv files 

### ISSUE THREAD

**Issue by asknet** [forcedotcom/SFDX-Data-Move-Utility#773]
Hi,

Thank you for the wonderful plugin!

Is it possible to add a new functionality to ScriptObject Object to generate a source CSV file? My use case is, to generate a source csv file in one of the object sets and use that source CSV file in another object set using property`useSourceCSVFile`

**Comment by hknokh** [comment]
Hello, @asknet

Thank you for your feature request.
I will review it as soon as possible and provide updates as they become available.

Cheers

**Comment by hknokh2** [comment]
Indeed, it appears a useful feature. I am putting it on my roadmap. I think it will even get a priority in the development backlog.

**Comment by asknet** [comment]
Appreciate your prompt reply and consideration 🙌

**Comment by asknet** [comment]
@hknokh Hi, I see the issue was auto-closed. I hope it is still under your radar.

**Comment by hknokh2** [comment]
Yes. It should be closed. I usually close all feature requests and tag them for future review. But as I've already said I can't  promise any specific time when or if it will be under the actual development. I will update you as soon as I can.
Thanks for the patience.

**Comment by hknokh** [comment]
Hello,

Thank you for the suggestion.
I reviewed this case again.
At this time, implementing this feature is not feasible.

Reasons:
- Generating source CSV as an additional orchestrated stage duplicates existing extraction paths and increases runtime complexity.
- Current architecture prioritizes direct source reads and established csvfile mode rather than new intermediate-generation flows.

If additional opportunity appears, I will revisit this case.
Thank you for understanding.

Best regards
