### ISSUE TITLE
Can updates ignore null values in csvs?

### ISSUE THREAD

**Issue by jack-bennett-osf** [forcedotcom/SFDX-Data-Move-Utility#857]
I'm currently running some update jobs within my current project where I need to update some existing records within Salesforce.
The csv file I have been provided has a lot of blank cells in the csv (where they aren't supposed to be blank). The data team has only provided me values that have changed. Existing values have been missed off the csv.
Based off that, is there anyway I can "ignore" blank cells, so that it doesn't null this value in Salesforce?

As part of BulkAPI, it says that null values should be ignored, unless you explicilty enter #N/A in each cell. This doesn't seem to be the case when running an update through SFDMU.
![image](https://github.com/user-attachments/assets/aa744a65-fbc5-4a74-9b66-5e5d05ab58dd)
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/datafiles_csv_valid_record_rows.htm?search_text=Empty%20field%20values

**Comment by hknokh** [comment]
Hello, @jack-bennett-osf

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment]
Hello,
This issue is fixed as of v4.35.1. You can refer to the following link for details:
https://help.sfdmu.com/examples/csv-import-export#example-4-resetting-target-field-values-using-csv-files
Now, #N/A will clear the target value, while a null (empty value in CSV) will retain the target (ignore update). Please update the plugin and check.

**Comment by jack-bennett-osf** [comment]
Hi @hknokh2,

I have just tried updating my SFDMU plugin to the latest version and running a test upsert, but it still seems to blank values in Salesforce when changing an existing value's cell to null.

![image](https://github.com/user-attachments/assets/506ff5bc-07d6-4b10-b8fe-6c995d61e82c)

Leaving a cell null AND changing a populated cell to #N/A will clear the respective values in Salesforce. Seems that the former is still not working as expected.

Below is a snippet of my query (minus a few fields). I have explicitly specified the Bulk API version, even though I know it defaults to 2.0 as per the documentation. In the csv file, I have just been adding/removing a PerOrg_ID__c value to test with. I also tried removing the excludeIdsFromCSVFiles attribute to see if this was clashing, but it wasn't.

{
    "objects": [
        {
            "query": "SELECT Name, Party_ID__c, PerOrg_ID__c FROM Account",
            "operation": "Upsert",
            "externalId": "Party_ID__c"        
        }
    ],
    "bulkApiVersion": "2.0",
    "excludeIdsFromCSVFiles": "true"
}

Kind regards,
Jack.

**Comment by hknokh2** [comment]
Since your record count is below 200 (the default `bulkThreshold`), SFDMU runs using the REST API, which clears values even if they are blank.  This behavior regarding #N/A vs NULLs  is only true in Bulk API

To ensure that the Bulk API is always enforced and the fix works, add the following configuration to your `export.json`:

```json
{
  "objects": [
    {
      "query": "SELECT Name, Party_ID__c, PerOrg_ID__c FROM Account",
      "operation": "Upsert",
      "externalId": "Party_ID__c"
    }
  ],
  "bulkApiVersion": "2.0",
  "excludeIdsFromCSVFiles": "true",
  "bulkThreshold": 0 
}
```
Resources:
https://help.sfdmu.com/examples/csv-import-export#example-4-resetting-target-field-values-using-csv-files
https://help.sfdmu.com/full-documentation/export-json-file-objects-specification/script-object#bulkthreshold-integer

**Comment by jack-bennett-osf** [comment]
@hknokh2 Ahh that makes sense now! Thank you so much for clarifying. It's now working as expected :)
Will close off. Thanks again!
