### ISSUE TITLE
[ FEATURE REQUEST] SFDMU depends on unsupported and outdated libraries.

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/SFDX-Data-Move-Utility#869]
**Describe the bug**
Just installed plugin and got many warnings during this process, here is an output:
```
PS D:\git> sf plugins install sfdmu
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for sfdmu.
Finished digital signature check.
npm warn deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated @oclif/command@1.8.36: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated @oclif/help@1.0.15: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated deep.clone@2.1.2: No longer maintained. Moved to https://npm.im/@reallyland/node_mod.
npm warn deprecated @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @oclif/config@1.18.16: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @oclif/config@1.18.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated soql-parser-js@1.2.1: This package has been moved to the @jetstreamapp organization starting on version 6.0.0. Update your dependency to use @jetstreamapp/soql-parser-js.
added 252 packages in 16s
```

**To Reproduce**
Unsinstall whole SF CLI so it remove also plugins.
Install SF CLI.
Install sfdx-git-delta with command ```sf plugins install sfdx-git-delta```

**Expected behavior**
Plugin install without warning.

**export.json**
Not applicable to this issue.

**Log file**
Not applicable to this issue.

**_target.csv** file.
Not applicable to this issue.

**Comment by hknokh** [comment]
Hello, @PawelWozniak

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by wrt83** [comment]
I would add to this that both alasql and madge are very outdates and contain multiple "high" level vulnerabilities. 

alasql latest is 4.5.1, sfdmu is on 0.6.4
madge latest is 8.0.0, sfdmu is on 3.8.0

**Comment by hknokh2** [comment]
Hello, 

All these vulnerabilities do not matter since the tool is used only locally. I do not plan to update dependencies in the near future, as it might require refactoring and regression tests due to breaking changes in the newest versions. If you have any doubts regarding security, please stop using sfdmu.

**Comment by PawelWozniak** [comment]
In my opinion since this tool is developed under Salesforce Developers official account and Salesforce repeatedly says that Trust is number one for them then security should be considered as important.

**Comment by hknokh2** [comment]
Ok. This is your opinion and understanding

**Comment by PawelWozniak** [comment]
I understand that fixing such dependency is complex as it can cause some side effects. I am glad that you improve this tool it is beneficial for everyone.

**Comment by hknokh** [comment]
Converted to "feature request".

I am closing this issue for now. I will review the feature request at a later time, but please note that there is no guarantee that this update will be implemented. I will provide further updates if there are any developments.

Best regards.

**Comment by hknokh** [comment]
> I would add to this that both alasql and madge are very outdates and contain multiple "high" level vulnerabilities.
> 
> alasql latest is 4.5.1, sfdmu is on 0.6.4 madge latest is 8.0.0, sfdmu is on 3.8.0

These dependencies has been updated to the latest version.
Generally, I'm working on moving the plugin to the V2 of the SF CLI which is based on @salesforce/core
Opened the new feature request for that:[Upgrade the SFDMU to V2 of SF CLI](https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/887)

**Comment by hknokh2** [comment]
Hello @PawelWozniak,

Thanks again for pointing out the outdated libraries used in the project.
I wanted to inform you that I’ve been working on converting SFDMU to the latest SF CLI ESM plugin template. However, since SFDMU was originally developed using the older SFDX CLI CommonJs architecture and relies on libraries that are not fully compatible with the latest SF CLI plugin architecture, the conversion process seems nearly impossible or extremely difficult. It would require almost a complete rewrite of the code.

My priority is to avoid any breaking changes or regressions, as SFDMU is actively used by a large number of organizations and businesses. Therefore, I prefer not to proceed with the upgrade at this time, as SFDMU continues to function well despite some minor warnings that may appear.

For now, I’ve postponed this upgrade, but it might be revisited later when it becomes more feasible.

**Comment by PawelWozniak** [comment]
@hknokh2 Thank you for the update. This tool works well so keep it going. Thank you.
