### ISSUE TITLE
[FEATURE REQUEST] - Upgrade the plugin to V2 of the SF CLI API

### ISSUE THREAD

**Issue by hknokh** [forcedotcom/SFDX-Data-Move-Utility#887]

**Comment by hknokh** [comment]
Hi

Thank you for your feature request. I am closing this issue for now. I will review the feature request at a later time, but please note that there is no guarantee that this update will be implemented. I will provide further updates if there are any developments.

Best regards.

**Comment by hknokh** [comment]
Hello, @hknokh

Thank you for your feature request.
I will review it as soon as possible and provide updates as they become available.

Cheers

**Comment by hknokh2** [comment]
Since SFDMU was developed a long time ago using the older SFDX CLI CommonJs architecture, converting it to the latest SF CLI ESM module format seems impossible or extremely difficult. It would require almost a complete rewrite of the code. Therefore, this upgrade has been postponed for future review, depending on its feasibility.
